In [1]:
pip install librosa

Collecting librosa
  Downloading librosa-0.10.2.post1-py3-none-any.whl.metadata (8.6 kB)
Collecting audioread>=2.1.9 (from librosa)
  Downloading audioread-3.0.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: numpy!=1.22.0,!=1.22.1,!=1.22.2,>=1.20.3 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.26.3)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.11.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.3.0)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.3.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (5.1.1)
Collecting numba>=0.51.0 (from librosa)
  Downloading numba-0.60.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Collecting soundfile>=0.12.1 (from librosa)
  Downloading soundfile-0.12.1-py2.py3-none-manylinux_2_31_x86_64.whl.metadata (14 kB)
Collecting pooch>=1.1 (from librosa)
  Downloading pooch-1.8.2-py3-none-any.whl.metadata (10 kB)
Collecting soxr>=0.3.2 (from librosa)
  Downloading soxr-0.5.0.post1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from librosa) (4.9.0)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.11/dist-packages (from librosa) (0.3)
Collecting msgpack>=1.0 (from librosa)
  Downloading msgpack-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba>=0.51.0->librosa)
  Downloading llvmlite-0.43.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa) (4.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa) (23.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa) (2.31.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.20.0->librosa) (3.2.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.11/dist-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2020.6.20)
Downloading librosa-0.10.2.post1-py3-none-any.whl (260 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.1/260.1 kB 17.5 MB/s eta 0:00:00
Downloading audioread-3.0.1-py3-none-any.whl (23 kB)
Downloading msgpack-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (403 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.7/403.7 kB 68.3 MB/s eta 0:00:00
Downloading numba-0.60.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 97.1 MB/s eta 0:00:00:00:01
Downloading pooch-1.8.2-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.6/64.6 kB 17.1 MB/s eta 0:00:00
Downloading soundfile-0.12.1-py2.py3-none-manylinux_2_31_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 103.6 MB/s eta 0:00:00
Downloading soxr-0.5.0.post1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.5/252.5 kB 46.1 MB/s eta 0:00:00
Downloading llvmlite-0.43.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 67.0 MB/s eta 0:00:00:00:0100:01
Installing collected packages: soxr, msgpack, llvmlite, audioread, soundfile, pooch, numba, librosa
Successfully installed audioread-3.0.1 librosa-0.10.2.post1 llvmlite-0.43.0 msgpack-1.1.0 numba-0.60.0 pooch-1.8.2 soundfile-0.12.1 soxr-0.5.0.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [1]:
DATASETPATH = '/notebooks/1/Quran_Ayat_public/audio_data/Abdul_Basit_Murattal_64kbps/001001.mp3'

In [2]:
import torch
import librosa
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
import os

# Define the constants
LANG_ID = "ar"
MODEL_ID = "jonatasgrosman/wav2vec2-large-xlsr-53-arabic"
audio_path = "/notebooks/1/Quran_Ayat_public/audio_data/Abdul_Basit_Murattal_64kbps/001001.mp3"

# Load the processor and model
processor = Wav2Vec2Processor.from_pretrained(MODEL_ID)
model = Wav2Vec2ForCTC.from_pretrained(MODEL_ID)

# Load the audio file using librosa
speech_array, sampling_rate = librosa.load(audio_path, sr=16_000)

# Process the audio file with the processor
inputs = processor(speech_array, sampling_rate=16_000, return_tensors="pt", padding=True)

# Pass the inputs through the model
with torch.no_grad():
    logits = model(inputs.input_values, attention_mask=inputs.attention_mask).logits

# Get the predicted ids
predicted_ids = torch.argmax(logits, dim=-1)

# Decode the ids to get the predicted sentence
predicted_sentence = processor.batch_decode(predicted_ids)

# Output the result
predicted_sentence

preprocessor_config.json:   0%|          | 0.00/158 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.56k [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/configuration_utils.py:381: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

vocab.json:   0%|          | 0.00/507 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

Ignored unknown kwarg option normalize
Ignored unknown kwarg option normalize
Ignored unknown kwarg option normalize
Ignored unknown kwarg option normalize

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Some weights of the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-arabic were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_v', 'wav2vec2.encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-arabic and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2024-10-21 16:20:26.534496: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-21 16:20:26.534564: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-21 16:20:26.622300: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-21 16:20:26.798499: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-21 16:20:28.405989: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

['بسم الله الرحمن الرحيم']

In [12]:
sourah_list = [
    "الفاتحة", "البقرة", "آل عمران", "النساء", "المائدة", "الأنعام", "الأعراف", "الأنفال", "التوبة", "يونس", 
    "هود", "يوسف", "الرعد", "إبراهيم", "الحجر", "النحل", "الإسراء", "الكهف", "مريم", "طه", 
    "الأنبياء", "الحج", "المؤمنون", "النور", "الفرقان", "الشعراء", "النمل", "القصص", "العنكبوت", "الروم", 
    "لقمان", "السجدة", "الأحزاب", "سبأ", "فاطر", "يس", "الصافات", "ص", "الزمر", "غافر", 
    "فصلت", "الشورى", "الزخرف", "الدخان", "الجاثية", "الأحقاف", "محمد", "الفتح", "الحجرات", "ق", 
    "الذاريات", "الطور", "النجم", "القمر", "الرحمن", "الواقعة", "الحديد", "المجادلة", "الحشر", "الممتحنة", 
    "الصف", "الجمعة", "المنافقون", "التغابن", "الطلاق", "التحريم", "الملك", "القلم", "الحاقة", "المعارج", 
    "نوح", "الجن", "المزمل", "المدثر", "القيامة", "الإنسان", "المرسلات", "النبأ", "النازعات", "عبس", 
    "التكوير", "الإنفطار", "المطففين", "الإنشقاق", "البروج", "الطارق", "الأعلى", "الغاشية", "الفجر", "البلد", 
    "الشمس", "الليل", "الضحى", "الشرح", "التين", "العلق", "القدر", "البينة", "الزلزلة", "العاديات", 
    "القارعة", "التكاثر", "العصر", "الهمزة", "الفيل", "قريش", "الماعون", "الكوثر", "الكافرون", "النصر", 
    "المسد", "الإخلاص", "الفلق", "الناس"
]

In [11]:
import json

ayat_map = json.load(open('/notebooks/1/Quran_Ayat_public/all_ayat.json'))
ayat_map['tafsir']

{'1_1': {'text': 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ'},
 '1_2': {'text': 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ'},
 '1_3': {'text': 'الرَّحْمَٰنِ الرَّحِيمِ'},
 '1_4': {'text': 'مَالِكِ يَوْمِ الدِّينِ'},
 '1_5': {'text': 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ'},
 '1_6': {'text': 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ'},
 '1_7': {'text': 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ'},
 '2_1': {'text': 'الم'},
 '2_2': {'text': 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ'},
 '2_3': {'text': 'الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ'},
 '2_4': {'text': 'وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ وَمَا أُنزِلَ مِن قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ'},
 '2_5': {'text': 'أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ'},
 '2_6': {'text': 'إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ'},
 '2_7': {'text': 'خَتَمَ اللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰ أَبْصَارِهِمْ غِشَاوَةٌ ۖ وَلَهُمْ عَذَابٌ عَظِيمٌ'},
 '2_8': {'text': 'وَمِنَ النَّاسِ مَن يَقُولُ آمَنَّا بِاللَّهِ وَبِالْيَوْمِ الْآخِرِ وَمَا هُم بِمُؤْمِنِينَ'},
 '2_9': {'text': 'يُخَادِعُونَ اللَّهَ وَالَّذِينَ آمَنُوا وَمَا يَخْدَعُونَ إِلَّا أَنفُسَهُمْ وَمَا يَشْعُرُونَ'},
 '2_10': {'text': 'فِي قُلُوبِهِم مَّرَضٌ فَزَادَهُمُ اللَّهُ مَرَضًا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌ بِمَا كَانُوا يَكْذِبُونَ'},
 '2_11': {'text': 'وَإِذَا قِيلَ لَهُمْ لَا تُفْسِدُوا فِي الْأَرْضِ قَالُوا إِنَّمَا نَحْنُ مُصْلِحُونَ'},
 '2_12': {'text': 'أَلَا إِنَّهُمْ هُمُ الْمُفْسِدُونَ وَلَٰكِن لَّا يَشْعُرُونَ'},
 '2_13': {'text': 'وَإِذَا قِيلَ لَهُمْ آمِنُوا كَمَا آمَنَ النَّاسُ قَالُوا أَنُؤْمِنُ كَمَا آمَنَ السُّفَهَاءُ ۗ أَلَا إِنَّهُمْ هُمُ السُّفَهَاءُ وَلَٰكِن لَّا يَعْلَمُونَ'},
 '2_14': {'text': 'وَإِذَا لَقُوا الَّذِينَ آمَنُوا قَالُوا آمَنَّا وَإِذَا خَلَوْا إِلَىٰ شَيَاطِينِهِمْ قَالُوا إِنَّا مَعَكُمْ إِنَّمَا نَحْنُ مُسْتَهْزِئُونَ'},
 '2_15': {'text': 'اللَّهُ يَسْتَهْزِئُ بِهِمْ وَيَمُدُّهُمْ فِي طُغْيَانِهِمْ يَعْمَهُونَ'},
 '2_16': {'text': 'أُولَٰئِكَ الَّذِينَ اشْتَرَوُا الضَّلَالَةَ بِالْهُدَىٰ فَمَا رَبِحَت تِّجَارَتُهُمْ وَمَا كَانُوا مُهْتَدِينَ'},
 '2_17': {'text': 'مَثَلُهُمْ كَمَثَلِ الَّذِي اسْتَوْقَدَ نَارًا فَلَمَّا أَضَاءَتْ مَا حَوْلَهُ ذَهَبَ اللَّهُ بِنُورِهِمْ وَتَرَكَهُمْ فِي ظُلُمَاتٍ لَّا يُبْصِرُونَ'},
 '2_18': {'text': 'صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ'},
 '2_19': {'text': 'أَوْ كَصَيِّبٍ مِّنَ السَّمَاءِ فِيهِ ظُلُمَاتٌ وَرَعْدٌ وَبَرْقٌ يَجْعَلُونَ أَصَابِعَهُمْ فِي آذَانِهِم مِّنَ الصَّوَاعِقِ حَذَرَ الْمَوْتِ ۚ وَاللَّهُ مُحِيطٌ بِالْكَافِرِينَ'},
 '2_20': {'text': 'يَكَادُ الْبَرْقُ يَخْطَفُ أَبْصَارَهُمْ ۖ كُلَّمَا أَضَاءَ لَهُم مَّشَوْا فِيهِ وَإِذَا أَظْلَمَ عَلَيْهِمْ قَامُوا ۚ وَلَوْ شَاءَ اللَّهُ لَذَهَبَ بِسَمْعِهِمْ وَأَبْصَارِهِمْ ۚ إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ'},
 '2_21': {'text': 'يَا أَيُّهَا النَّاسُ اعْبُدُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ وَالَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ'},
 '2_22': {'text': 'الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً وَأَنزَلَ مِنَ السَّمَاءِ مَاءً فَأَخْرَجَ بِهِ مِنَ الثَّمَرَاتِ رِزْقًا لَّكُمْ ۖ فَلَا تَجْعَلُوا لِلَّهِ أَندَادًا وَأَنتُمْ تَعْلَمُونَ'},
 '2_23': {'text': 'وَإِن كُنتُمْ فِي رَيْبٍ مِّمَّا نَزَّلْنَا عَلَىٰ عَبْدِنَا فَأْتُوا بِسُورَةٍ مِّن مِّثْلِهِ وَادْعُوا شُهَدَاءَكُم مِّن دُونِ اللَّهِ إِن كُنتُمْ صَادِقِينَ'},
 '2_24': {'text': 'فَإِن لَّمْ تَفْعَلُوا وَلَن تَفْعَلُوا فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ ۖ أُعِدَّتْ لِلْكَافِرِينَ'},
 '2_25': {'text': 'وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ ۖ كُلَّمَا رُزِقُوا مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا هَٰذَا الَّذِي رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا بِهِ مُتَشَابِهًا ۖ وَلَهُمْ فِيهَا أَزْوَاجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَالِدُونَ'},
 '2_26': {'text': '۞ إِنَّ اللَّهَ لَا يَسْتَحْيِي أَن يَضْرِبَ مَثَلًا مَّا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا الَّذِينَ آمَنُوا فَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا الَّذِينَ كَفَرُوا فَيَقُولُونَ مَاذَا أَرَادَ اللَّهُ بِهَٰذَا مَثَلًا ۘ يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِ إِلَّا الْفَاسِقِينَ'},
 '2_27': {'text': 'الَّذِينَ يَنقُضُونَ عَهْدَ اللَّهِ مِن بَعْدِ مِيثَاقِهِ وَيَقْطَعُونَ مَا أَمَرَ اللَّهُ بِهِ أَن يُوصَلَ وَيُفْسِدُونَ فِي الْأَرْضِ ۚ أُولَٰئِكَ هُمُ الْخَاسِرُونَ'},
 '2_28': {'text': 'كَيْفَ تَكْفُرُونَ بِاللَّهِ وَكُنتُمْ أَمْوَاتًا فَأَحْيَاكُمْ ۖ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ'},
 '2_29': {'text': 'هُوَ الَّذِي خَلَقَ لَكُم مَّا فِي الْأَرْضِ جَمِيعًا ثُمَّ اسْتَوَىٰ إِلَى السَّمَاءِ فَسَوَّاهُنَّ سَبْعَ سَمَاوَاتٍ ۚ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ'},
 '2_30': {'text': 'وَإِذْ قَالَ رَبُّكَ لِلْمَلَائِكَةِ إِنِّي جَاعِلٌ فِي الْأَرْضِ خَلِيفَةً ۖ قَالُوا أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ الدِّمَاءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّي أَعْلَمُ مَا لَا تَعْلَمُونَ'},
 '2_31': {'text': 'وَعَلَّمَ آدَمَ الْأَسْمَاءَ كُلَّهَا ثُمَّ عَرَضَهُمْ عَلَى الْمَلَائِكَةِ فَقَالَ أَنبِئُونِي بِأَسْمَاءِ هَٰؤُلَاءِ إِن كُنتُمْ صَادِقِينَ'},
 '2_32': {'text': 'قَالُوا سُبْحَانَكَ لَا عِلْمَ لَنَا إِلَّا مَا عَلَّمْتَنَا ۖ إِنَّكَ أَنتَ الْعَلِيمُ الْحَكِيمُ'},
 '2_33': {'text': 'قَالَ يَا آدَمُ أَنبِئْهُم بِأَسْمَائِهِمْ ۖ فَلَمَّا أَنبَأَهُم بِأَسْمَائِهِمْ قَالَ أَلَمْ أَقُل لَّكُمْ إِنِّي أَعْلَمُ غَيْبَ السَّمَاوَاتِ وَالْأَرْضِ وَأَعْلَمُ مَا تُبْدُونَ وَمَا كُنتُمْ تَكْتُمُونَ'},
 '2_34': {'text': 'وَإِذْ قُلْنَا لِلْمَلَائِكَةِ اسْجُدُوا لِآدَمَ فَسَجَدُوا إِلَّا إِبْلِيسَ أَبَىٰ وَاسْتَكْبَرَ وَكَانَ مِنَ الْكَافِرِينَ'},
 '2_35': {'text': 'وَقُلْنَا يَا آدَمُ اسْكُنْ أَنتَ وَزَوْجُكَ الْجَنَّةَ وَكُلَا مِنْهَا رَغَدًا حَيْثُ شِئْتُمَا وَلَا تَقْرَبَا هَٰذِهِ الشَّجَرَةَ فَتَكُونَا مِنَ الظَّالِمِينَ'},
 '2_36': {'text': 'فَأَزَلَّهُمَا الشَّيْطَانُ عَنْهَا فَأَخْرَجَهُمَا مِمَّا كَانَا فِيهِ ۖ وَقُلْنَا اهْبِطُوا بَعْضُكُمْ لِبَعْضٍ عَدُوٌّ ۖ وَلَكُمْ فِي الْأَرْضِ مُسْتَقَرٌّ وَمَتَاعٌ إِلَىٰ حِينٍ'},
 '2_37': {'text': 'فَتَلَقَّىٰ آدَمُ مِن رَّبِّهِ كَلِمَاتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُ هُوَ التَّوَّابُ الرَّحِيمُ'},
 '2_38': {'text': 'قُلْنَا اهْبِطُوا مِنْهَا جَمِيعًا ۖ فَإِمَّا يَأْتِيَنَّكُم مِّنِّي هُدًى فَمَن تَبِعَ هُدَايَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ'},
 '2_39': {'text': 'وَالَّذِينَ كَفَرُوا وَكَذَّبُوا بِآيَاتِنَا أُولَٰئِكَ أَصْحَابُ النَّارِ ۖ هُمْ فِيهَا خَالِدُونَ'},
 '2_40': {'text': 'يَا بَنِي إِسْرَائِيلَ اذْكُرُوا نِعْمَتِيَ الَّتِي أَنْعَمْتُ عَلَيْكُمْ وَأَوْفُوا بِعَهْدِي أُوفِ بِعَهْدِكُمْ وَإِيَّايَ فَارْهَبُونِ'},
 '2_41': {'text': 'وَآمِنُوا بِمَا أَنزَلْتُ مُصَدِّقًا لِّمَا مَعَكُمْ وَلَا تَكُونُوا أَوَّلَ كَافِرٍ بِهِ ۖ وَلَا تَشْتَرُوا بِآيَاتِي ثَمَنًا قَلِيلًا وَإِيَّايَ فَاتَّقُونِ'},
 '2_42': {'text': 'وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ وَتَكْتُمُوا الْحَقَّ وَأَنتُمْ تَعْلَمُونَ'},
 '2_43': {'text': 'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ وَارْكَعُوا مَعَ الرَّاكِعِينَ'},
 '2_44': {'text': '۞ أَتَأْمُرُونَ النَّاسَ بِالْبِرِّ وَتَنسَوْنَ أَنفُسَكُمْ وَأَنتُمْ تَتْلُونَ الْكِتَابَ ۚ أَفَلَا تَعْقِلُونَ'},
 '2_45': {'text': 'وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى الْخَاشِعِينَ'},
 '2_46': {'text': 'الَّذِينَ يَظُنُّونَ أَنَّهُم مُّلَاقُو رَبِّهِمْ وَأَنَّهُمْ إِلَيْهِ رَاجِعُونَ'},
 '2_47': {'text': 'يَا بَنِي إِسْرَائِيلَ اذْكُرُوا نِعْمَتِيَ الَّتِي أَنْعَمْتُ عَلَيْكُمْ وَأَنِّي فَضَّلْتُكُمْ عَلَى الْعَالَمِينَ'},
 '2_48': {'text': 'وَاتَّقُوا يَوْمًا لَّا تَجْزِي نَفْسٌ عَن نَّفْسٍ شَيْئًا وَلَا يُقْبَلُ مِنْهَا شَفَاعَةٌ وَلَا يُؤْخَذُ مِنْهَا عَدْلٌ وَلَا هُمْ يُنصَرُونَ'},
 '2_49': {'text': 'وَإِذْ نَجَّيْنَاكُم مِّنْ آلِ فِرْعَوْنَ يَسُومُونَكُمْ سُوءَ الْعَذَابِ يُذَبِّحُونَ أَبْنَاءَكُمْ وَيَسْتَحْيُونَ نِسَاءَكُمْ ۚ وَفِي ذَٰلِكُم بَلَاءٌ مِّن رَّبِّكُمْ عَظِيمٌ'},
 '2_50': {'text': 'وَإِذْ فَرَقْنَا بِكُمُ الْبَحْرَ فَأَنجَيْنَاكُمْ وَأَغْرَقْنَا آلَ فِرْعَوْنَ وَأَنتُمْ تَنظُرُونَ'},
 '2_51': {'text': 'وَإِذْ وَاعَدْنَا مُوسَىٰ أَرْبَعِينَ لَيْلَةً ثُمَّ اتَّخَذْتُمُ الْعِجْلَ مِن بَعْدِهِ وَأَنتُمْ ظَالِمُونَ'},
 '2_52': {'text': 'ثُمَّ عَفَوْنَا عَنكُم مِّن بَعْدِ ذَٰلِكَ لَعَلَّكُمْ تَشْكُرُونَ'},
 '2_53': {'text': 'وَإِذْ آتَيْنَا مُوسَى الْكِتَابَ وَالْفُرْقَانَ لَعَلَّكُمْ تَهْتَدُونَ'},
 '2_54': {'text': 'وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِ يَا قَوْمِ إِنَّكُمْ ظَلَمْتُمْ أَنفُسَكُم بِاتِّخَاذِكُمُ الْعِجْلَ فَتُوبُوا إِلَىٰ بَارِئِكُمْ فَاقْتُلُوا أَنفُسَكُمْ ذَٰلِكُمْ خَيْرٌ لَّكُمْ عِندَ بَارِئِكُمْ فَتَابَ عَلَيْكُمْ ۚ إِنَّهُ هُوَ التَّوَّابُ الرَّحِيمُ'},
 '2_55': {'text': 'وَإِذْ قُلْتُمْ يَا مُوسَىٰ لَن نُّؤْمِنَ لَكَ حَتَّىٰ نَرَى اللَّهَ جَهْرَةً فَأَخَذَتْكُمُ الصَّاعِقَةُ وَأَنتُمْ تَنظُرُونَ'},
 '2_56': {'text': 'ثُمَّ بَعَثْنَاكُم مِّن بَعْدِ مَوْتِكُمْ لَعَلَّكُمْ تَشْكُرُونَ'},
 '2_57': {'text': 'وَظَلَّلْنَا عَلَيْكُمُ الْغَمَامَ وَأَنزَلْنَا عَلَيْكُمُ الْمَنَّ وَالسَّلْوَىٰ ۖ كُلُوا مِن طَيِّبَاتِ مَا رَزَقْنَاكُمْ ۖ وَمَا ظَلَمُونَا وَلَٰكِن كَانُوا أَنفُسَهُمْ يَظْلِمُونَ'},
 '2_58': {'text': 'وَإِذْ قُلْنَا ادْخُلُوا هَٰذِهِ الْقَرْيَةَ فَكُلُوا مِنْهَا حَيْثُ شِئْتُمْ رَغَدًا وَادْخُلُوا الْبَابَ سُجَّدًا وَقُولُوا حِطَّةٌ نَّغْفِرْ لَكُمْ خَطَايَاكُمْ ۚ وَسَنَزِيدُ الْمُحْسِنِينَ'},
 '2_59': {'text': 'فَبَدَّلَ الَّذِينَ ظَلَمُوا قَوْلًا غَيْرَ الَّذِي قِيلَ لَهُمْ فَأَنزَلْنَا عَلَى الَّذِينَ ظَلَمُوا رِجْزًا مِّنَ السَّمَاءِ بِمَا كَانُوا يَفْسُقُونَ'},
 '2_60': {'text': '۞ وَإِذِ اسْتَسْقَىٰ مُوسَىٰ لِقَوْمِهِ فَقُلْنَا اضْرِب بِّعَصَاكَ الْحَجَرَ ۖ فَانفَجَرَتْ مِنْهُ اثْنَتَا عَشْرَةَ عَيْنًا ۖ قَدْ عَلِمَ كُلُّ أُنَاسٍ مَّشْرَبَهُمْ ۖ كُلُوا وَاشْرَبُوا مِن رِّزْقِ اللَّهِ وَلَا تَعْثَوْا فِي الْأَرْضِ مُفْسِدِينَ'},
 '2_61': {'text': 'وَإِذْ قُلْتُمْ يَا مُوسَىٰ لَن نَّصْبِرَ عَلَىٰ طَعَامٍ وَاحِدٍ فَادْعُ لَنَا رَبَّكَ يُخْرِجْ لَنَا مِمَّا تُنبِتُ الْأَرْضُ مِن بَقْلِهَا وَقِثَّائِهَا وَفُومِهَا وَعَدَسِهَا وَبَصَلِهَا ۖ قَالَ أَتَسْتَبْدِلُونَ الَّذِي هُوَ أَدْنَىٰ بِالَّذِي هُوَ خَيْرٌ ۚ اهْبِطُوا مِصْرًا فَإِنَّ لَكُم مَّا سَأَلْتُمْ ۗ وَضُرِبَتْ عَلَيْهِمُ الذِّلَّةُ وَالْمَسْكَنَةُ وَبَاءُوا بِغَضَبٍ مِّنَ اللَّهِ ۗ ذَٰلِكَ بِأَنَّهُمْ كَانُوا يَكْفُرُونَ بِآيَاتِ اللَّهِ وَيَقْتُلُونَ النَّبِيِّينَ بِغَيْرِ الْحَقِّ ۗ ذَٰلِكَ بِمَا عَصَوا وَّكَانُوا يَعْتَدُونَ'},
 '2_62': {'text': 'إِنَّ الَّذِينَ آمَنُوا وَالَّذِينَ هَادُوا وَالنَّصَارَىٰ وَالصَّابِئِينَ مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ وَعَمِلَ صَالِحًا فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ'},
 '2_63': {'text': 'وَإِذْ أَخَذْنَا مِيثَاقَكُمْ وَرَفَعْنَا فَوْقَكُمُ الطُّورَ خُذُوا مَا آتَيْنَاكُم بِقُوَّةٍ وَاذْكُرُوا مَا فِيهِ لَعَلَّكُمْ تَتَّقُونَ'},
 '2_64': {'text': 'ثُمَّ تَوَلَّيْتُم مِّن بَعْدِ ذَٰلِكَ ۖ فَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ وَرَحْمَتُهُ لَكُنتُم مِّنَ الْخَاسِرِينَ'},
 '2_65': {'text': 'وَلَقَدْ عَلِمْتُمُ الَّذِينَ اعْتَدَوْا مِنكُمْ فِي السَّبْتِ فَقُلْنَا لَهُمْ كُونُوا قِرَدَةً خَاسِئِينَ'},
 '2_66': {'text': 'فَجَعَلْنَاهَا نَكَالًا لِّمَا بَيْنَ يَدَيْهَا وَمَا خَلْفَهَا وَمَوْعِظَةً لِّلْمُتَّقِينَ'},
 '2_67': {'text': 'وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِ إِنَّ اللَّهَ يَأْمُرُكُمْ أَن تَذْبَحُوا بَقَرَةً ۖ قَالُوا أَتَتَّخِذُنَا هُزُوًا ۖ قَالَ أَعُوذُ بِاللَّهِ أَنْ أَكُونَ مِنَ الْجَاهِلِينَ'},
 '2_68': {'text': 'قَالُوا ادْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا هِيَ ۚ قَالَ إِنَّهُ يَقُولُ إِنَّهَا بَقَرَةٌ لَّا فَارِضٌ وَلَا بِكْرٌ عَوَانٌ بَيْنَ ذَٰلِكَ ۖ فَافْعَلُوا مَا تُؤْمَرُونَ'},
 '2_69': {'text': 'قَالُوا ادْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا لَوْنُهَا ۚ قَالَ إِنَّهُ يَقُولُ إِنَّهَا بَقَرَةٌ صَفْرَاءُ فَاقِعٌ لَّوْنُهَا تَسُرُّ النَّاظِرِينَ'},
 '2_70': {'text': 'قَالُوا ادْعُ لَنَا رَبَّكَ يُبَيِّن لَّنَا مَا هِيَ إِنَّ الْبَقَرَ تَشَابَهَ عَلَيْنَا وَإِنَّا إِن شَاءَ اللَّهُ لَمُهْتَدُونَ'},
 '2_71': {'text': 'قَالَ إِنَّهُ يَقُولُ إِنَّهَا بَقَرَةٌ لَّا ذَلُولٌ تُثِيرُ الْأَرْضَ وَلَا تَسْقِي الْحَرْثَ مُسَلَّمَةٌ لَّا شِيَةَ فِيهَا ۚ قَالُوا الْآنَ جِئْتَ بِالْحَقِّ ۚ فَذَبَحُوهَا وَمَا كَادُوا يَفْعَلُونَ'},
 '2_72': {'text': 'وَإِذْ قَتَلْتُمْ نَفْسًا فَادَّارَأْتُمْ فِيهَا ۖ وَاللَّهُ مُخْرِجٌ مَّا كُنتُمْ تَكْتُمُونَ'},
 '2_73': {'text': 'فَقُلْنَا اضْرِبُوهُ بِبَعْضِهَا ۚ كَذَٰلِكَ يُحْيِي اللَّهُ الْمَوْتَىٰ وَيُرِيكُمْ آيَاتِهِ لَعَلَّكُمْ تَعْقِلُونَ'},
 '2_74': {'text': 'ثُمَّ قَسَتْ قُلُوبُكُم مِّن بَعْدِ ذَٰلِكَ فَهِيَ كَالْحِجَارَةِ أَوْ أَشَدُّ قَسْوَةً ۚ وَإِنَّ مِنَ الْحِجَارَةِ لَمَا يَتَفَجَّرُ مِنْهُ الْأَنْهَارُ ۚ وَإِنَّ مِنْهَا لَمَا يَشَّقَّقُ فَيَخْرُجُ مِنْهُ الْمَاءُ ۚ وَإِنَّ مِنْهَا لَمَا يَهْبِطُ مِنْ خَشْيَةِ اللَّهِ ۗ وَمَا اللَّهُ بِغَافِلٍ عَمَّا تَعْمَلُونَ'},
 '2_75': {'text': '۞ أَفَتَطْمَعُونَ أَن يُؤْمِنُوا لَكُمْ وَقَدْ كَانَ فَرِيقٌ مِّنْهُمْ يَسْمَعُونَ كَلَامَ اللَّهِ ثُمَّ يُحَرِّفُونَهُ مِن بَعْدِ مَا عَقَلُوهُ وَهُمْ يَعْلَمُونَ'},
 '2_76': {'text': 'وَإِذَا لَقُوا الَّذِينَ آمَنُوا قَالُوا آمَنَّا وَإِذَا خَلَا بَعْضُهُمْ إِلَىٰ بَعْضٍ قَالُوا أَتُحَدِّثُونَهُم بِمَا فَتَحَ اللَّهُ عَلَيْكُمْ لِيُحَاجُّوكُم بِهِ عِندَ رَبِّكُمْ ۚ أَفَلَا تَعْقِلُونَ'},
 '2_77': {'text': 'أَوَلَا يَعْلَمُونَ أَنَّ اللَّهَ يَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ'},
 '2_78': {'text': 'وَمِنْهُمْ أُمِّيُّونَ لَا يَعْلَمُونَ الْكِتَابَ إِلَّا أَمَانِيَّ وَإِنْ هُمْ إِلَّا يَظُنُّونَ'},
 '2_79': {'text': 'فَوَيْلٌ لِّلَّذِينَ يَكْتُبُونَ الْكِتَابَ بِأَيْدِيهِمْ ثُمَّ يَقُولُونَ هَٰذَا مِنْ عِندِ اللَّهِ لِيَشْتَرُوا بِهِ ثَمَنًا قَلِيلًا ۖ فَوَيْلٌ لَّهُم مِّمَّا كَتَبَتْ أَيْدِيهِمْ وَوَيْلٌ لَّهُم مِّمَّا يَكْسِبُونَ'},
 '2_80': {'text': 'وَقَالُوا لَن تَمَسَّنَا النَّارُ إِلَّا أَيَّامًا مَّعْدُودَةً ۚ قُلْ أَتَّخَذْتُمْ عِندَ اللَّهِ عَهْدًا فَلَن يُخْلِفَ اللَّهُ عَهْدَهُ ۖ أَمْ تَقُولُونَ عَلَى اللَّهِ مَا لَا تَعْلَمُونَ'},
 '2_81': {'text': 'بَلَىٰ مَن كَسَبَ سَيِّئَةً وَأَحَاطَتْ بِهِ خَطِيئَتُهُ فَأُولَٰئِكَ أَصْحَابُ النَّارِ ۖ هُمْ فِيهَا خَالِدُونَ'},
 '2_82': {'text': 'وَالَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أُولَٰئِكَ أَصْحَابُ الْجَنَّةِ ۖ هُمْ فِيهَا خَالِدُونَ'},
 '2_83': {'text': 'وَإِذْ أَخَذْنَا مِيثَاقَ بَنِي إِسْرَائِيلَ لَا تَعْبُدُونَ إِلَّا اللَّهَ وَبِالْوَالِدَيْنِ إِحْسَانًا وَذِي الْقُرْبَىٰ وَالْيَتَامَىٰ وَالْمَسَاكِينِ وَقُولُوا لِلنَّاسِ حُسْنًا وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ ثُمَّ تَوَلَّيْتُمْ إِلَّا قَلِيلًا مِّنكُمْ وَأَنتُم مُّعْرِضُونَ'},
 '2_84': {'text': 'وَإِذْ أَخَذْنَا مِيثَاقَكُمْ لَا تَسْفِكُونَ دِمَاءَكُمْ وَلَا تُخْرِجُونَ أَنفُسَكُم مِّن دِيَارِكُمْ ثُمَّ أَقْرَرْتُمْ وَأَنتُمْ تَشْهَدُونَ'},
 '2_85': {'text': 'ثُمَّ أَنتُمْ هَٰؤُلَاءِ تَقْتُلُونَ أَنفُسَكُمْ وَتُخْرِجُونَ فَرِيقًا مِّنكُم مِّن دِيَارِهِمْ تَظَاهَرُونَ عَلَيْهِم بِالْإِثْمِ وَالْعُدْوَانِ وَإِن يَأْتُوكُمْ أُسَارَىٰ تُفَادُوهُمْ وَهُوَ مُحَرَّمٌ عَلَيْكُمْ إِخْرَاجُهُمْ ۚ أَفَتُؤْمِنُونَ بِبَعْضِ الْكِتَابِ وَتَكْفُرُونَ بِبَعْضٍ ۚ فَمَا جَزَاءُ مَن يَفْعَلُ ذَٰلِكَ مِنكُمْ إِلَّا خِزْيٌ فِي الْحَيَاةِ الدُّنْيَا ۖ وَيَوْمَ الْقِيَامَةِ يُرَدُّونَ إِلَىٰ أَشَدِّ الْعَذَابِ ۗ وَمَا اللَّهُ بِغَافِلٍ عَمَّا تَعْمَلُونَ'},
 '2_86': {'text': 'أُولَٰئِكَ الَّذِينَ اشْتَرَوُا الْحَيَاةَ الدُّنْيَا بِالْآخِرَةِ ۖ فَلَا يُخَفَّفُ عَنْهُمُ الْعَذَابُ وَلَا هُمْ يُنصَرُونَ'},
 '2_87': {'text': 'وَلَقَدْ آتَيْنَا مُوسَى الْكِتَابَ وَقَفَّيْنَا مِن بَعْدِهِ بِالرُّسُلِ ۖ وَآتَيْنَا عِيسَى ابْنَ مَرْيَمَ الْبَيِّنَاتِ وَأَيَّدْنَاهُ بِرُوحِ الْقُدُسِ ۗ أَفَكُلَّمَا جَاءَكُمْ رَسُولٌ بِمَا لَا تَهْوَىٰ أَنفُسُكُمُ اسْتَكْبَرْتُمْ فَفَرِيقًا كَذَّبْتُمْ وَفَرِيقًا تَقْتُلُونَ'},
 '2_88': {'text': 'وَقَالُوا قُلُوبُنَا غُلْفٌ ۚ بَل لَّعَنَهُمُ اللَّهُ بِكُفْرِهِمْ فَقَلِيلًا مَّا يُؤْمِنُونَ'},
 '2_89': {'text': 'وَلَمَّا جَاءَهُمْ كِتَابٌ مِّنْ عِندِ اللَّهِ مُصَدِّقٌ لِّمَا مَعَهُمْ وَكَانُوا مِن قَبْلُ يَسْتَفْتِحُونَ عَلَى الَّذِينَ كَفَرُوا فَلَمَّا جَاءَهُم مَّا عَرَفُوا كَفَرُوا بِهِ ۚ فَلَعْنَةُ اللَّهِ عَلَى الْكَافِرِينَ'},
 '2_90': {'text': 'بِئْسَمَا اشْتَرَوْا بِهِ أَنفُسَهُمْ أَن يَكْفُرُوا بِمَا أَنزَلَ اللَّهُ بَغْيًا أَن يُنَزِّلَ اللَّهُ مِن فَضْلِهِ عَلَىٰ مَن يَشَاءُ مِنْ عِبَادِهِ ۖ فَبَاءُوا بِغَضَبٍ عَلَىٰ غَضَبٍ ۚ وَلِلْكَافِرِينَ عَذَابٌ مُّهِينٌ'},
 '2_91': {'text': 'وَإِذَا قِيلَ لَهُمْ آمِنُوا بِمَا أَنزَلَ اللَّهُ قَالُوا نُؤْمِنُ بِمَا أُنزِلَ عَلَيْنَا وَيَكْفُرُونَ بِمَا وَرَاءَهُ وَهُوَ الْحَقُّ مُصَدِّقًا لِّمَا مَعَهُمْ ۗ قُلْ فَلِمَ تَقْتُلُونَ أَنبِيَاءَ اللَّهِ مِن قَبْلُ إِن كُنتُم مُّؤْمِنِينَ'},
 '2_92': {'text': '۞ وَلَقَدْ جَاءَكُم مُّوسَىٰ بِالْبَيِّنَاتِ ثُمَّ اتَّخَذْتُمُ الْعِجْلَ مِن بَعْدِهِ وَأَنتُمْ ظَالِمُونَ'},
 '2_93': {'text': 'وَإِذْ أَخَذْنَا مِيثَاقَكُمْ وَرَفَعْنَا فَوْقَكُمُ الطُّورَ خُذُوا مَا آتَيْنَاكُم بِقُوَّةٍ وَاسْمَعُوا ۖ قَالُوا سَمِعْنَا وَعَصَيْنَا وَأُشْرِبُوا فِي قُلُوبِهِمُ الْعِجْلَ بِكُفْرِهِمْ ۚ قُلْ بِئْسَمَا يَأْمُرُكُم بِهِ إِيمَانُكُمْ إِن كُنتُم مُّؤْمِنِينَ'},
 '2_94': {'text': 'قُلْ إِن كَانَتْ لَكُمُ الدَّارُ الْآخِرَةُ عِندَ اللَّهِ خَالِصَةً مِّن دُونِ النَّاسِ فَتَمَنَّوُا الْمَوْتَ إِن كُنتُمْ صَادِقِينَ'},
 '2_95': {'text': 'وَلَن يَتَمَنَّوْهُ أَبَدًا بِمَا قَدَّمَتْ أَيْدِيهِمْ ۗ وَاللَّهُ عَلِيمٌ بِالظَّالِمِينَ'},
 '2_96': {'text': 'وَلَتَجِدَنَّهُمْ أَحْرَصَ النَّاسِ عَلَىٰ حَيَاةٍ وَمِنَ الَّذِينَ أَشْرَكُوا ۚ يَوَدُّ أَحَدُهُمْ لَوْ يُعَمَّرُ أَلْفَ سَنَةٍ وَمَا هُوَ بِمُزَحْزِحِهِ مِنَ الْعَذَابِ أَن يُعَمَّرَ ۗ وَاللَّهُ بَصِيرٌ بِمَا يَعْمَلُونَ'},
 '2_97': {'text': 'قُلْ مَن كَانَ عَدُوًّا لِّجِبْرِيلَ فَإِنَّهُ نَزَّلَهُ عَلَىٰ قَلْبِكَ بِإِذْنِ اللَّهِ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَهُدًى وَبُشْرَىٰ لِلْمُؤْمِنِينَ'},
 '2_98': {'text': 'مَن كَانَ عَدُوًّا لِّلَّهِ وَمَلَائِكَتِهِ وَرُسُلِهِ وَجِبْرِيلَ وَمِيكَالَ فَإِنَّ اللَّهَ عَدُوٌّ لِّلْكَافِرِينَ'},
 '2_99': {'text': 'وَلَقَدْ أَنزَلْنَا إِلَيْكَ آيَاتٍ بَيِّنَاتٍ ۖ وَمَا يَكْفُرُ بِهَا إِلَّا الْفَاسِقُونَ'},
 '2_100': {'text': 'أَوَكُلَّمَا عَاهَدُوا عَهْدًا نَّبَذَهُ فَرِيقٌ مِّنْهُم ۚ بَلْ أَكْثَرُهُمْ لَا يُؤْمِنُونَ'},
 '2_101': {'text': 'وَلَمَّا جَاءَهُمْ رَسُولٌ مِّنْ عِندِ اللَّهِ مُصَدِّقٌ لِّمَا مَعَهُمْ نَبَذَ فَرِيقٌ مِّنَ الَّذِينَ أُوتُوا الْكِتَابَ كِتَابَ اللَّهِ وَرَاءَ ظُهُورِهِمْ كَأَنَّهُمْ لَا يَعْلَمُونَ'},
 '2_102': {'text': 'وَاتَّبَعُوا مَا تَتْلُو الشَّيَاطِينُ عَلَىٰ مُلْكِ سُلَيْمَانَ ۖ وَمَا كَفَرَ سُلَيْمَانُ وَلَٰكِنَّ الشَّيَاطِينَ كَفَرُوا يُعَلِّمُونَ النَّاسَ السِّحْرَ وَمَا أُنزِلَ عَلَى الْمَلَكَيْنِ بِبَابِلَ هَارُوتَ وَمَارُوتَ ۚ وَمَا يُعَلِّمَانِ مِنْ أَحَدٍ حَتَّىٰ يَقُولَا إِنَّمَا نَحْنُ فِتْنَةٌ فَلَا تَكْفُرْ ۖ فَيَتَعَلَّمُونَ مِنْهُمَا مَا يُفَرِّقُونَ بِهِ بَيْنَ الْمَرْءِ وَزَوْجِهِ ۚ وَمَا هُم بِضَارِّينَ بِهِ مِنْ أَحَدٍ إِلَّا بِإِذْنِ اللَّهِ ۚ وَيَتَعَلَّمُونَ مَا يَضُرُّهُمْ وَلَا يَنفَعُهُمْ ۚ وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ ۚ وَلَبِئْسَ مَا شَرَوْا بِهِ أَنفُسَهُمْ ۚ لَوْ كَانُوا يَعْلَمُونَ'},
 '2_103': {'text': 'وَلَوْ أَنَّهُمْ آمَنُوا وَاتَّقَوْا لَمَثُوبَةٌ مِّنْ عِندِ اللَّهِ خَيْرٌ ۖ لَّوْ كَانُوا يَعْلَمُونَ'},
 '2_104': {'text': 'يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَقُولُوا رَاعِنَا وَقُولُوا انظُرْنَا وَاسْمَعُوا ۗ وَلِلْكَافِرِينَ عَذَابٌ أَلِيمٌ'},
 '2_105': {'text': 'مَّا يَوَدُّ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَلَا الْمُشْرِكِينَ أَن يُنَزَّلَ عَلَيْكُم مِّنْ خَيْرٍ مِّن رَّبِّكُمْ ۗ وَاللَّهُ يَخْتَصُّ بِرَحْمَتِهِ مَن يَشَاءُ ۚ وَاللَّهُ ذُو الْفَضْلِ الْعَظِيمِ'},
 '2_106': {'text': '۞ مَا نَنسَخْ مِنْ آيَةٍ أَوْ نُنسِهَا نَأْتِ بِخَيْرٍ مِّنْهَا أَوْ مِثْلِهَا ۗ أَلَمْ تَعْلَمْ أَنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ'},
 '2_107': {'text': 'أَلَمْ تَعْلَمْ أَنَّ اللَّهَ لَهُ مُلْكُ السَّمَاوَاتِ وَالْأَرْضِ ۗ وَمَا لَكُم مِّن دُونِ اللَّهِ مِن وَلِيٍّ وَلَا نَصِيرٍ'},
 '2_108': {'text': 'أَمْ تُرِيدُونَ أَن تَسْأَلُوا رَسُولَكُمْ كَمَا سُئِلَ مُوسَىٰ مِن قَبْلُ ۗ وَمَن يَتَبَدَّلِ الْكُفْرَ بِالْإِيمَانِ فَقَدْ ضَلَّ سَوَاءَ السَّبِيلِ'},
 '2_109': {'text': 'وَدَّ كَثِيرٌ مِّنْ أَهْلِ الْكِتَابِ لَوْ يَرُدُّونَكُم مِّن بَعْدِ إِيمَانِكُمْ كُفَّارًا حَسَدًا مِّنْ عِندِ أَنفُسِهِم مِّن بَعْدِ مَا تَبَيَّنَ لَهُمُ الْحَقُّ ۖ فَاعْفُوا وَاصْفَحُوا حَتَّىٰ يَأْتِيَ اللَّهُ بِأَمْرِهِ ۗ إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ'},

In [16]:
import pandas as pd
transcript_df = pd.read_csv('/notebooks/1/Quran_Ayat_public/transcripts.tsv', sep='\t')
transcript_df['PATH'] = transcript_df['PATH'].apply(lambda x: x.replace('${DATASET_PATH}','/notebooks/1'))
transcript_df['SOURAH'] = transcript_df['PATH'].apply(lambda x: sourah_list[int(x.split('/')[-1].replace('.mp3','')[:3]) - 1])
transcript_df

,PATH,DURATION,TRANSCRIPT,SOURAH
0,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,6.321633,بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ,الفاتحة
1,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,10.161633,الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ,الفاتحة
2,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,8.698776,الرَّحْمَٰنِ الرَّحِيمِ,الفاتحة
3,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,7.340408,مَالِكِ يَوْمِ الدِّينِ,الفاتحة
4,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,11.572245,إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ,الفاتحة
...,...,...,...,...
232360,/notebooks/1/Quran_Ayat_public/audio_data/wars...,2.037551,مَلِكِ النَّاسِ,الناس
232361,/notebooks/1/Quran_Ayat_public/audio_data/wars...,3.604898,إِلَٰهِ النَّاسِ,الناس
232362,/notebooks/1/Quran_Ayat_public/audio_data/wars...,5.355102,مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ,الناس
232363,/notebooks/1/Quran_Ayat_public/audio_data/wars...,5.067755,الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ,الناس
232364,/notebooks/1/Quran_Ayat_public/audio_data/wars...,4.963265,مِنَ الْجِنَّةِ وَالنَّاسِ,الناس

In [17]:
transcript_df.groupby('SOURAH').count()

          PATH  DURATION  TRANSCRIPT
SOURAH
آل عمران  7400      7400        7400
إبراهيم   1924      1924        1924
الأحزاب   2701      2701        2701
الأحقاف   1330      1330        1330
الأعراف   7622      7622        7622
...        ...       ...         ...
نوح       1064      1064        1064
هود       4551      4551        4551
يس        3071      3071        3071
يوسف      4107      4107        4107
يونس      4033      4033        4033

[114 rows x 3 columns]

In [20]:
poc_transcript_df = transcript_df[transcript_df['SOURAH'] == 'الفاتحة'].reset_index(drop=True)
poc_transcript_df

,PATH,DURATION,TRANSCRIPT,SOURAH
0,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,6.321633,بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ,الفاتحة
1,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,10.161633,الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ,الفاتحة
2,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,8.698776,الرَّحْمَٰنِ الرَّحِيمِ,الفاتحة
3,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,7.340408,مَالِكِ يَوْمِ الدِّينِ,الفاتحة
4,/notebooks/1/Quran_Ayat_public/audio_data/Abdu...,11.572245,إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ,الفاتحة
...,...,...,...,...
261,/notebooks/1/Quran_Ayat_public/audio_data/wars...,3.500408,الرَّحْمَٰنِ الرَّحِيمِ,الفاتحة
262,/notebooks/1/Quran_Ayat_public/audio_data/wars...,3.787755,مَالِكِ يَوْمِ الدِّينِ,الفاتحة
263,/notebooks/1/Quran_Ayat_public/audio_data/wars...,3.474286,إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ,الفاتحة
264,/notebooks/1/Quran_Ayat_public/audio_data/wars...,3.787755,اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ,الفاتحة
265,/notebooks/1/Quran_Ayat_public/audio_data/wars...,12.277551,صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ...,الفاتحة

In [4]:
import librosa
from IPython.display import Audio

# Load the audio file
audio_path = "/notebooks/1/Quran_Ayat_public/audio_data/Abdul_Basit_Murattal_64kbps/001001.mp3"
speech_array, sampling_rate = librosa.load(audio_path, sr=16000)

# Play the audio
Audio(speech_array, rate=sampling_rate)

In [16]:

# Function to process a batch of files
def process_audio_batch(dataset):
    predictions = []
    for index, row in dataset.iterrows():
        # Load the audio file using librosa
        speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
        
        # Process the audio file with the processor
        inputs = processor(speech_array, sampling_rate=16_000, return_tensors="pt", padding=True)

        # Pass the inputs through the model
        with torch.no_grad():
            logits = model(inputs.input_values, attention_mask=inputs.attention_mask).logits

        # Get the predicted ids and decode them
        predicted_ids = torch.argmax(logits, dim=-1)
        predicted_sentence = processor.batch_decode(predicted_ids)
        
        # Store the predicted sentence
        predictions.append(predicted_sentence[0])
    
    return predictions

BATCH_SIZE = 10
# Evaluate the batch
random_rows = transcript_df.sample(BATCH_SIZE).reset_index(drop=True)
predicted_sentences = process_audio_batch(random_rows)

# Print the reference and predictions for each audio sample
for i, predicted_sentence in enumerate(predicted_sentences):
    print("-" * 100)
    print("Reference:", random_rows["TRANSCRIPT"][i])
    print("Prediction:", predicted_sentence)

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

----------------------------------------------------------------------------------------------------
Reference: إِنَّ رَبَّكَ هُوَ الْخَلَّاقُ الْعَلِيمُ إِنَّ رَبَّكَ هُوَ الْخَلَّاقُ الْعَلِيمُ
Prediction: إِنَّ رَبَّكَ هُو القَلابُ اللّليم إيَ وضبَكَهُوالقٌ لّاكُ عي
----------------------------------------------------------------------------------------------------
Reference: وَالَّذِينَ يَقُولُونَ رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ ۖ إِنَّ عَذَابَهَا كَانَ غَرَامًا
Prediction: وَالَّذِينَ يَقُولُنَ رَبَّنَ صْرِفَانَّا عَذَابَ جَاهًانَّمَ إِنَّ عَذَابَاهَا كَانَ غَرَامًا
----------------------------------------------------------------------------------------------------
Reference: وَلَوْ شِئْنَا لَبَعَثْنَا فِي كُلِّ قَرْيَةٍ نَّذِيرًا
Prediction: وَلَوْ شِئْنَا لَبَعَثْنَا فِي كُلِّ قَرْيَةٍنَذِيرًا
----------------------------------------------------------------------------------------------------
Reference: وَأَتِمُّوا الْحَجَّ وَالْعُمْرَةَ لِلَّهِ ۚ فَإِنْ أُحْصِرْتُمْ فَمَا اسْتَيْسَرَ مِنَ الْهَدْيِ ۖ وَلَا تَحْلِقُوا رُءُوسَكُمْ حَتَّىٰ يَبْلُغَ الْهَدْيُ مَحِلَّهُ ۚ فَمَن كَانَ مِنكُم مَّرِيضًا أَوْ بِهِ أَذًى مِّن رَّأْسِهِ فَفِدْيَةٌ مِّن صِيَامٍ أَوْ صَدَقَةٍ أَوْ نُسُكٍ ۚ فَإِذَا أَمِنتُمْ فَمَن تَمَتَّعَ بِالْعُمْرَةِ إِلَى الْحَجِّ فَمَا اسْتَيْسَرَ مِنَ الْهَدْيِ ۚ فَمَن لَّمْ يَجِدْ فَصِيَامُ ثَلَاثَةِ أَيَّامٍ فِي الْحَجِّ وَسَبْعَةٍ إِذَا رَجَعْتُمْ ۗ تِلْكَ عَشَرَةٌ كَامِلَةٌ ۗ ذَٰلِكَ لِمَن لَّمْ يَكُنْ أَهْلُهُ حَاضِرِي الْمَسْجِدِ الْحَرَامِ ۚ وَاتَّقُوا اللَّهَ وَاعْلَمُوا أَنَّ اللَّهَ شَدِيدُ الْعِقَابِ
Prediction: وَأَتِمُ لْحَدَّ وَالْعُمرَةَ لِلَّهِ فَإِنْ أُحْصِرْتُمْ فَمَزْتَيْسَرَ مِنَ الْهَدِ وَلَا تَحْلِقُورءُوسَكُمْ حَتَّى يَبْلُغًا لهَذِيُ مَحِلَّة فَمَنْ كانَ مِكُم مَرِيظًان أَوْ بِهِ أَذَممِنْ رَسِّهِ فَفِذِيَةُمِنْصِيامٍ أَوْ صَدَقَةٍ أَوْ نُسُ فَإِذا أَمِتُمْ فَمَتَمَتَّعَ بِ الْعُمرَةِ إِلَى لْحَجِّ فَمَزْتَيْسَرَ مِنَ الْهَدِ فَمَنْ لَمْ يَدِدْ فَصِامُ ثَلاثَةِ أَيَّامٍ فِي الْحَجِّ وَسَبَعَةٍ إِذا رَدَعْتُمْ تِلكَ عَجْرَةُ كامِلَةٌ ذَلِكَ لِمَنْ لَمْ يَكُنْ أَهْلُهُ حاظِرِ لْمَزْجِدٍ حَرم وَاتَّقُوا اللَّهَ وَاعْلَمُو أَنَّ اللَّهَ شَدِيدٌ لعِقابٍ
----------------------------------------------------------------------------------------------------
Reference: وَأَوْرَثْنَا الْقَوْمَ الَّذِينَ كَانُوا يُسْتَضْعَفُونَ مَشَارِقَ الْأَرْضِ وَمَغَارِبَهَا الَّتِي بَارَكْنَا فِيهَا ۖ وَتَمَّتْ كَلِمَتُ رَبِّكَ الْحُسْنَىٰ عَلَىٰ بَنِي إِسْرَائِيلَ بِمَا صَبَرُوا ۖ وَدَمَّرْنَا مَا كَانَ يَصْنَعُ فِرْعَوْنُ وَقَوْمُهُ وَمَا كَانُوا يَعْرِشُونَ
Prediction: وَأَوْرَصْنَ الْقَوْمَ الَّذِينَ كَانُواا يُسْتَضْعَفُونَ مَشَارِقًا الْأَرضِ وَمَا ضَائِبَالَّتِي بَارَتْنَا فِيهَا وَتَمَّتْ كَلِمَةُ رَبِّكَ الْحُسْنَى عَلَى بَنِ إِصرَ إِلَ بِمَا صَبَوا وَدَمَرْنَا مَا كَانَ يَصْنَعُ فِي الْعَوْن وَقَه وَمَا كَانُو يَعْرِشُونَ
----------------------------------------------------------------------------------------------------
Reference: إِنَّ هَٰؤُلَاءِ مُتَبَّرٌ مَّا هُمْ فِيهِ وَبَاطِلٌ مَّا كَانُوا يَعْمَلُونَ
Prediction: إِنَّ هَاأُلَاءِ مُتَبَّرُم مَا وُهُمْ فِيهِ وبَاطِلُ مَا كَانُوا يَعْمَلُون
----------------------------------------------------------------------------------------------------
Reference: كُلَّمَا أَرَادُوا أَن يَخْرُجُوا مِنْهَا مِنْ غَمٍّ أُعِيدُوا فِيهَا وَذُوقُوا عَذَابَ الْحَرِيقِ
Prediction: قلما أرادوا أن يخرجوا منها من غم أعيد فيها وأذوق وعذابا حريق
----------------------------------------------------------------------------------------------------
Reference: وَيْلٌ يَوْمَئِذٍ لِّلْمُكَذِّبِينَ
Prediction: وَيْنُي يَوْمَئِذٍ ذٍلمُكَذِّبي
----------------------------------------------------------------------------------------------------
Reference: إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا
Prediction: إِنَ جَهَنمَّمَ كَانَتْ مِرْصَادَا
----------------------------------------------------------------------------------------------------
Reference: إِنَّا نَحْنُ نُحْيِي الْمَوْتَىٰ وَنَكْتُبُ مَا قَدَّمُوا وَآثَارَهُمْ ۚ وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ فِي إِمَامٍ مُّبِينٍ
Prediction: إِنَّا نَحْنُ نُحْيِي الْمَوْتَى وَنَكْتُبُ مَا قَدَّمُ وَأفَارَهُمْ وَكُلَّ شَيإِنْ أَحْصَيْنَاهُ فِي إِمَا مِن مُبِينٍ

In [15]:
random_rows

,PATH,DURATION,TRANSCRIPT
133403,/notebooks/1/Quran_Ayat_public/audio_data/Alaf...,7.627755,الَّذِينَ هُمْ فِي غَمْرَةٍ سَاهُونَ
68070,/notebooks/1/Quran_Ayat_public/audio_data/Saoo...,14.367347,مَا كَانَ لِنَبِيٍّ أَن يَكُونَ لَهُ أَسْرَىٰ ...
214179,/notebooks/1/Quran_Ayat_public/audio_data/wars...,15.046531,وَكَمْ أَهْلَكْنَا قَبْلَهُم مِّن قَرْنٍ هُمْ ...
61639,/notebooks/1/Quran_Ayat_public/audio_data/Saoo...,5.825306,أُبَلِّغُكُمْ رِسَالَاتِ رَبِّي وَأَنَا لَكُمْ...
202278,/notebooks/1/Quran_Ayat_public/audio_data/Muhs...,4.336327,وَيْلٌ يَوْمَئِذٍ لِّلْمُكَذِّبِينَ
203158,/notebooks/1/Quran_Ayat_public/audio_data/Mahe...,2.586122,وَالْعَادِيَاتِ ضَبْحًا
101591,/notebooks/1/Quran_Ayat_public/audio_data/Fare...,10.128000,وَأَمْطَرْنَا عَلَيْهِم مَّطَرًا ۖ فَسَاءَ مَط...
44689,/notebooks/1/Quran_Ayat_public/audio_data/Mins...,27.245714,وَذَرُوا ظَاهِرَ الْإِثْمِ وَبَاطِنَهُ ۚ إِنَّ...
96389,/notebooks/1/Quran_Ayat_public/audio_data/Hani...,5.120000,قَالَ فِرْعَوْنُ وَمَا رَبُّ الْعَالَمِينَ
81970,/notebooks/1/Quran_Ayat_public/audio_data/Muha...,9.168980,إِنَّ فِي ذَٰلِكَ لَآيَةً لِّلْمُؤْمِنِينَ

# Model Initial evaluation

In [21]:
pip install jiwer

Collecting jiwer
  Downloading jiwer-3.0.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: click<9.0.0,>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from jiwer) (8.1.7)
Collecting rapidfuzz<4,>=3 (from jiwer)
  Downloading rapidfuzz-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading jiwer-3.0.4-py3-none-any.whl (21 kB)
Downloading rapidfuzz-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 59.8 MB/s eta 0:00:00a 0:00:01
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-3.0.4 rapidfuzz-3.10.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [22]:
import librosa
import torch
from jiwer import wer, cer

# Function to process a batch of files
def process_audio_batch(dataset):
    predictions = []
    for index, row in dataset.iterrows():
        # Load the audio file using librosa
        speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
        
        # Process the audio file with the processor
        inputs = processor(speech_array, sampling_rate=16_000, return_tensors="pt", padding=True)

        # Pass the inputs through the model
        with torch.no_grad():
            logits = model(inputs.input_values, attention_mask=inputs.attention_mask).logits

        # Get the predicted ids and decode them
        predicted_ids = torch.argmax(logits, dim=-1)
        predicted_sentence = processor.batch_decode(predicted_ids)
        
        # Store the predicted sentence
        predictions.append(predicted_sentence[0])
    
    return predictions

# Function to evaluate the predictions using Word Error Rate (WER) and Character Error Rate (CER)
def evaluate_model(dataset, predictions):
    # Initialize lists to store reference and predicted sentences
    references = dataset["TRANSCRIPT"].tolist()
    predicted = predictions
    
    # Calculate WER and CER
    wer_score = wer(references, predicted)
    cer_score = cer(references, predicted)
    
    print(f"Word Error Rate (WER): {wer_score * 100:.2f}%")
    print(f"Character Error Rate (CER): {cer_score * 100:.2f}%")
    
    # Print reference and prediction side-by-side for inspection
    for i, predicted_sentence in enumerate(predicted):
        print("-" * 100)
        print(f"Reference [{i}]:", references[i])
        print(f"Prediction [{i}]:", predicted_sentence)

# Iterate over the entire dataset and evaluate every 10 samples
def evaluate_in_batches(dataset, batch_size=10):
    total_samples = len(dataset)
    for i in range(0, total_samples, batch_size):
        # Select the current batch of data
        batch_data = dataset.iloc[i:i+batch_size].reset_index(drop=True)
        
        # Process the batch and get predictions
        predicted_sentences = process_audio_batch(batch_data)
        
        # Evaluate the model predictions every 10 samples
        print(f"\nEvaluating samples {i+1} to {min(i+batch_size, total_samples)}:")
        evaluate_model(batch_data, predicted_sentences)

# Load the dataset filtered by Surah 'الفاتحة'
poc_transcript_df = transcript_df[transcript_df['SOURAH'] == 'الفاتحة'].reset_index(drop=True)

# Evaluate on all the data, calculating results every 10 samples
evaluate_in_batches(poc_transcript_df, batch_size=10)

Evaluating samples 1 to 10:
Word Error Rate (WER): 102.56%
Character Error Rate (CER): 49.21%
----------------------------------------------------------------------------------------------------
Reference [0]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: بسم الله الرحم للرحيم
----------------------------------------------------------------------------------------------------
Reference [1]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [1]: الْحَمدُ لِلدَّايِ رَبِّلعالَمِ
----------------------------------------------------------------------------------------------------
Reference [2]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: أررحمانررحيب
----------------------------------------------------------------------------------------------------
Reference [3]: مَالِكِ يَوْمِ الدِّينِ
Prediction [3]: مَالِيكيمِند
----------------------------------------------------------------------------------------------------
Reference [4]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [4]: إِيَّا كَانَمُودٌ وَإِيا كَنَ ستَع
----------------------------------------------------------------------------------------------------
Reference [5]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [5]: إِنْ دِينَ الصِرَاقًامُوستَقِ
----------------------------------------------------------------------------------------------------
Reference [6]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [6]: صِرَاطًان لَذِينَا أَنَّرَ أَمْتَرَلَ إِهِ غَمِييللْمَضُو بِعَادَ إِود إم
----------------------------------------------------------------------------------------------------
Reference [7]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [8]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [8]: الحمد لله رب العالمن
----------------------------------------------------------------------------------------------------
Reference [9]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: الرَّحْمَنِ الرَّحِيمِ

Evaluating samples 11 to 20:
Word Error Rate (WER): 94.87%
Character Error Rate (CER): 53.28%
----------------------------------------------------------------------------------------------------
Reference [0]: مَالِكِ يَوْمِ الدِّينِ
Prediction [0]: مَالِكِ يَوْمِ الدِّينِ
----------------------------------------------------------------------------------------------------
Reference [1]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [1]: إيا ك نعبد وإياك نستعيم
----------------------------------------------------------------------------------------------------
Reference [2]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [2]: إِهدِنَا الصِّرَاطَ الْمُستَقِيم
----------------------------------------------------------------------------------------------------
Reference [3]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [3]: صرَاطَى الَّذِينَ أَنَعَمْتَ عَلَيهِمْ غيرِ المغذُوبِ عَلَيْهِمْ ولضني
----------------------------------------------------------------------------------------------------
Reference [4]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [5]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [5]: إممينهكنوممنمعلدإلي
----------------------------------------------------------------------------------------------------
Reference [6]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: نأمرولملكليليلنكحي
----------------------------------------------------------------------------------------------------
Reference [7]: مَالِكِ يَوْمِ الدِّينِ
Prediction [7]: أمتتذ لي يودلليلي
----------------------------------------------------------------------------------------------------
Reference [8]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [8]: إذلعممممم للجدس محيمني
----------------------------------------------------------------------------------------------------
Reference [9]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [9]: تب ررقوق سإيإيي

Evaluating samples 21 to 30:
Word Error Rate (WER): 102.17%
Character Error Rate (CER): 52.01%
----------------------------------------------------------------------------------------------------
Reference [0]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [0]: بربرحوكنننممممنعمدي يينأككنممنممممإممنولللمل
----------------------------------------------------------------------------------------------------
Reference [1]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [2]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [2]: الحمدُ لله ربّ العالم
----------------------------------------------------------------------------------------------------
Reference [3]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [4]: مَالِكِ يَوْمِ الدِّينِ
Prediction [4]: مالك يوم الدين
----------------------------------------------------------------------------------------------------
Reference [5]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [5]: إيا كن عبد وإيا كان استعيم
----------------------------------------------------------------------------------------------------
Reference [6]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [6]: إهدِنَ الصراطَ المستقي
----------------------------------------------------------------------------------------------------
Reference [7]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [7]: صراط الّذين أنعمتَ عليهم غير مغضوب عليهم  ولضول
----------------------------------------------------------------------------------------------------
Reference [8]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: بسم الله الرحم رحيم
----------------------------------------------------------------------------------------------------
Reference [9]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [9]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمي

Evaluating samples 31 to 40:
Word Error Rate (WER): 94.74%
Character Error Rate (CER): 32.97%
----------------------------------------------------------------------------------------------------
Reference [0]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: الرَّحْمَنِ الرَّحِيم
----------------------------------------------------------------------------------------------------
Reference [1]: مَالِكِ يَوْمِ الدِّينِ
Prediction [1]: مَالِكِ يَوْمِ الدِّي
----------------------------------------------------------------------------------------------------
Reference [2]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [2]: إيَاك نَعبُدُ وإيَا كَ نَستَعين
----------------------------------------------------------------------------------------------------
Reference [3]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [3]: إهدِنَا الصِّرَاطَ الْمُستَقِيمَِ
----------------------------------------------------------------------------------------------------
Reference [4]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [4]: صِرَاطَ الَّذِينَ أَنْعُمْتَ عَلَيْْهِمْ غَيْرِ الْمَظْلُوبِ عَلَيْهِمْ وَلَبالِّي
----------------------------------------------------------------------------------------------------
Reference [5]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [6]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [6]: الحمدُ لله ورضضِ العَلم
----------------------------------------------------------------------------------------------------
Reference [7]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: أَالْرَّحْمَانِ الرَّئِيهِ
----------------------------------------------------------------------------------------------------
Reference [8]: مَالِكِ يَوْمِ الدِّينِ
Prediction [8]: مَا عَلَيكِ يَوْمٌ مِنْ ْضِهم
----------------------------------------------------------------------------------------------------
Reference [9]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [9]: إيا كن عقرورهلا كنت دالن

Evaluating samples 41 to 50:
Word Error Rate (WER): 135.56%
Character Error Rate (CER): 53.93%
----------------------------------------------------------------------------------------------------
Reference [0]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [0]: لن اصرا قهلمستقيه
----------------------------------------------------------------------------------------------------
Reference [1]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [1]: صيرلى قال العذر نا أفنعم الدارى علينا إلي م الغير من النوض أم ف عاده بعل مالهم ووة العليم
----------------------------------------------------------------------------------------------------
Reference [2]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: بسم الله ررحمانروحيم
----------------------------------------------------------------------------------------------------
Reference [3]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [3]: الحمد لل هي رب العالمين
----------------------------------------------------------------------------------------------------
Reference [4]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: أرحماني راحيم
----------------------------------------------------------------------------------------------------
Reference [5]: مَالِكِ يَوْمِ الدِّينِ
Prediction [5]: ما لتِ يوم الدن
----------------------------------------------------------------------------------------------------
Reference [6]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [6]: إيا كان عنبود وإيا كان ستعين
----------------------------------------------------------------------------------------------------
Reference [7]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [7]: إه دِين لصرا قا المستقيم
----------------------------------------------------------------------------------------------------
Reference [8]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [8]: صِمرَ أَقْاى لَّذِينَ أَنْ عَمتَ عَلَيهِم غير لمَوضُوبِي عالَيهم ولَضُلِن
----------------------------------------------------------------------------------------------------
Reference [9]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: بِسْمِ اللَّهِ الرَّحْمََنِ الرَّحِ

Evaluating samples 51 to 60:
Word Error Rate (WER): 105.26%
Character Error Rate (CER): 34.88%
----------------------------------------------------------------------------------------------------
Reference [0]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [0]: الحمدُو لِله رب العالم
----------------------------------------------------------------------------------------------------
Reference [1]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [2]: مَالِكِ يَوْمِ الدِّينِ
Prediction [2]: مالك يومِ لدِّ
----------------------------------------------------------------------------------------------------
Reference [3]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [3]: إِيَّا كَنَعْمُدُ وَإِيَا كانَ اسْتَعِي
----------------------------------------------------------------------------------------------------
Reference [4]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [4]: إهْدِينَ الصِرَاطَة الْمُسْتَقِيَ
----------------------------------------------------------------------------------------------------
Reference [5]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [5]: صراطا لذين أن عمت عليهم غير المغضوب عليهم ولا ضالن
----------------------------------------------------------------------------------------------------
Reference [6]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [7]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [7]: أَلْ حَمْدُو لِلَّهِ رَبٍّ لْعَالَمِينِ
----------------------------------------------------------------------------------------------------
Reference [8]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: أَالرَحْمَنِ الرَّحِمٍ
----------------------------------------------------------------------------------------------------
Reference [9]: مَالِكِ يَوْمِ الدِّينِ
Prediction [9]: مَالِكِ يَومِ الدِّينِ

Evaluating samples 61 to 70:
Word Error Rate (WER): 111.11%
Character Error Rate (CER): 37.81%
----------------------------------------------------------------------------------------------------
Reference [0]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [0]: إيا كان أعبد وإيا كان استعين
----------------------------------------------------------------------------------------------------
Reference [1]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [1]: بِنَ الصِّرَاطَا الْمُسْتَقِيمِ
----------------------------------------------------------------------------------------------------
Reference [2]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [2]: صِرَاطً الَّذِينَ أَنْعَمْتَ عَلَيهِمْ غَيرٍِ الْمَغْبُنبِ عَلَيهِمْ وَلَبُانِّنِ
----------------------------------------------------------------------------------------------------
Reference [3]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [4]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [4]: االحمد لله رب العالمين
----------------------------------------------------------------------------------------------------
Reference [5]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: أالرَّحمنِ الرَّحيم
----------------------------------------------------------------------------------------------------
Reference [6]: مَالِكِ يَوْمِ الدِّينِ
Prediction [6]: مالكي يوم الدين
----------------------------------------------------------------------------------------------------
Reference [7]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [7]: إياك نع بدو وإيا كان ستعين
----------------------------------------------------------------------------------------------------
Reference [8]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [8]: إه دِين الصراطَ المُستقيم
----------------------------------------------------------------------------------------------------
Reference [9]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [9]: صراطَ الّذين أَنعمت عليهِم غَيرِ المَغضوب عليهِم ولا لضا ولن

[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (736) too large for available bit count (728)
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (768) too large for available bit count (736)

Evaluating samples 71 to 80:
Word Error Rate (WER): 105.13%
Character Error Rate (CER): 38.22%
----------------------------------------------------------------------------------------------------
Reference [0]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [1]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [1]: أَلْحَمْدُ لِلَّهِ رَبٍّ العَالمِينَ
----------------------------------------------------------------------------------------------------
Reference [2]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [3]: مَالِكِ يَوْمِ الدِّينِ
Prediction [3]: مالكِ يومِ الدّينِ
----------------------------------------------------------------------------------------------------
Reference [4]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [4]: إيا ك نعبد وإياك نزدعين
----------------------------------------------------------------------------------------------------
Reference [5]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [5]: إهدنا الصراط المجتقيم
----------------------------------------------------------------------------------------------------
Reference [6]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [6]: صراطا لذين أن عمت عليهم غيرٍ المغضوبِ عليهم ولا الضالن
----------------------------------------------------------------------------------------------------
Reference [7]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: بِسْمِ اللَّهِ الرَّحْمَ أَنِرُ رَحِي
----------------------------------------------------------------------------------------------------
Reference [8]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [8]: أَلْحَمْذُولِلِلَهِ رَبٍّ عَالَ مِ
----------------------------------------------------------------------------------------------------
Reference [9]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: الرَّحْمَانِرُ رَحِي

[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (928) too large for available bit count (920)
[src/libmpg123/layer3.c:INT123_do_layer3():1801] error: dequantization failed!
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (2016) too large for available bit count (1856)
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (960) too large for available bit count (928)
[src/libmpg123/layer3.c:INT123_do_layer3():1801] error: dequantization failed!

Evaluating samples 81 to 90:
Word Error Rate (WER): 115.38%
Character Error Rate (CER): 40.94%
----------------------------------------------------------------------------------------------------
Reference [0]: مَالِكِ يَوْمِ الدِّينِ
Prediction [0]: مَالِكِ يَومِ الدِّي
----------------------------------------------------------------------------------------------------
Reference [1]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [1]: إِيَّا كَنَ عْبُودُ وَإِيَا كَانَ اسْتَرَنِي
----------------------------------------------------------------------------------------------------
Reference [2]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [2]: إهْ دِينَ الصِيرَاقَى لِلْمُسْتَقِي
----------------------------------------------------------------------------------------------------
Reference [3]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [3]: صِرَاقَالَّذِي نَأَلْ عَمْت عَلَيهِمْ وَيْرٍلمَغْضُهُب عَلَهِمْ وَلَوا
----------------------------------------------------------------------------------------------------
Reference [4]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: بسم الله الرحمن الرحي
----------------------------------------------------------------------------------------------------
Reference [5]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [5]: الحمدُ لِله رب العالمينِ
----------------------------------------------------------------------------------------------------
Reference [6]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: الرَّشْ مَا لِرضَّحِيم
----------------------------------------------------------------------------------------------------
Reference [7]: مَالِكِ يَوْمِ الدِّينِ
Prediction [7]: ما أرك يومِ الدِّي
----------------------------------------------------------------------------------------------------
Reference [8]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [8]: إيا كان أعبود وإيا كان استعين
----------------------------------------------------------------------------------------------------
Reference [9]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [9]: اهدِن الصراطة المستقيم

[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (992) too large for available bit count (928)

Evaluating samples 91 to 100:
Word Error Rate (WER): 91.30%
Character Error Rate (CER): 32.37%
----------------------------------------------------------------------------------------------------
Reference [0]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [0]: صِرَاطَ الَذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيرِ الْمَغْضُوبِ عَلَيْهٍ وَلَا لضَال
----------------------------------------------------------------------------------------------------
Reference [1]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [2]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [2]: الْحَمْدُ لِلَّنِ رَبِ العَالَم
----------------------------------------------------------------------------------------------------
Reference [3]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: ععض الرحمن يمرحيم
----------------------------------------------------------------------------------------------------
Reference [4]: مَالِكِ يَوْمِ الدِّينِ
Prediction [4]: ما علمتني عون الدّين
----------------------------------------------------------------------------------------------------
Reference [5]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [5]: إياكل عبد وإيا كان استاعيين
----------------------------------------------------------------------------------------------------
Reference [6]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [6]: ادِرَا الصِّرَافًا الْمُسْتَقِيمِ
----------------------------------------------------------------------------------------------------
Reference [7]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [7]: لصِرَافًا الَّذِينَ أَنَعَمْتَع عَلَيْهِ غَيرٍ لْمَوْضُوبِ عَلَيْهِ وَلَضَنِ
----------------------------------------------------------------------------------------------------
Reference [8]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِي
----------------------------------------------------------------------------------------------------
Reference [9]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [9]: لْحَمْدُ لِمنَهِ رَبِّ الْعَاالَمٍ

Evaluating samples 101 to 110:
Word Error Rate (WER): 94.74%
Character Error Rate (CER): 32.97%
----------------------------------------------------------------------------------------------------
Reference [0]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [1]: مَالِكِ يَوْمِ الدِّينِ
Prediction [1]: مَالِكِ يَوْمِ الدِّي
----------------------------------------------------------------------------------------------------
Reference [2]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [2]: إِياكَ نَعبدُ وإِياكنَ ستعِلٍ
----------------------------------------------------------------------------------------------------
Reference [3]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [3]: إهبِنَ الصِرَا قَلْ مُستطِم
----------------------------------------------------------------------------------------------------
Reference [4]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [4]: صِرَاقَ الَّذِينَ أَنْعَمْتَ عَلَيهِمْ غَيْرٍ لمَغْضُوبِ عَليهِمْ وَلا ضَّلن
----------------------------------------------------------------------------------------------------
Reference [5]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [6]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [6]: الْحَمْدُ لِلَهِ ربِّ العالَمنِ
----------------------------------------------------------------------------------------------------
Reference [7]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [8]: مَالِكِ يَوْمِ الدِّينِ
Prediction [8]: مالث يون الدين
----------------------------------------------------------------------------------------------------
Reference [9]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [9]: إيا ك نعبد وإياك نستعين

Evaluating samples 111 to 120:
Word Error Rate (WER): 120.00%
Character Error Rate (CER): 45.17%
----------------------------------------------------------------------------------------------------
Reference [0]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [0]: اهدِينَا الصراطَ المُستتِلم
----------------------------------------------------------------------------------------------------
Reference [1]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [1]: صِرَاطَى الَّذِينَ أَنْعَمْتَ عَلَيهِمْ غَيرِ الْمَغْضُوبِ عَلَيْهِمْ ولَضَّاوَللِينِ
----------------------------------------------------------------------------------------------------
Reference [2]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [3]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [3]: لحمدون لله رب لعال من
----------------------------------------------------------------------------------------------------
Reference [4]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: أرح مانير وحيم
----------------------------------------------------------------------------------------------------
Reference [5]: مَالِكِ يَوْمِ الدِّينِ
Prediction [5]: مَالكِيَه مِن الدِّين
----------------------------------------------------------------------------------------------------
Reference [6]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [6]: إيا كانَ عبُّد وإيا كانَ ستاعن
----------------------------------------------------------------------------------------------------
Reference [7]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [7]: إهدِي نَ لصي را طاني مَوس تكيم
----------------------------------------------------------------------------------------------------
Reference [8]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [8]: صراطا لذي ناآنع لمتى عىلى هم غر لمغضو بيعل عيه مول رب لن
----------------------------------------------------------------------------------------------------
Reference [9]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: بسم الله الرحمن الرحيم

Evaluating samples 121 to 130:
Word Error Rate (WER): 86.84%
Character Error Rate (CER): 34.88%
----------------------------------------------------------------------------------------------------
Reference [0]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [0]: الحمد لله رب العالمين
----------------------------------------------------------------------------------------------------
Reference [1]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [2]: مَالِكِ يَوْمِ الدِّينِ
Prediction [2]: مالك يوم الدين
----------------------------------------------------------------------------------------------------
Reference [3]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [3]: إياك نَعبد وإِيا كَنَستَعين
----------------------------------------------------------------------------------------------------
Reference [4]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [4]: إِهدنا الصراط المستقيم
----------------------------------------------------------------------------------------------------
Reference [5]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [5]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْغَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا ضَّالِّيْ
----------------------------------------------------------------------------------------------------
Reference [6]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: بسم الله الرحمن الرح
----------------------------------------------------------------------------------------------------
Reference [7]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [7]: الحمدُ لِلهِ ربٍّ عالمٍ
----------------------------------------------------------------------------------------------------
Reference [8]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: الرَّحْمَنِ الرَّحِي
----------------------------------------------------------------------------------------------------
Reference [9]: مَالِكِ يَوْمِ الدِّينِ
Prediction [9]: مالك يوم الدي

Evaluating samples 131 to 140:
Word Error Rate (WER): 95.56%
Character Error Rate (CER): 31.99%
----------------------------------------------------------------------------------------------------
Reference [0]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [0]: إياك نعبد وإياك نستعي
----------------------------------------------------------------------------------------------------
Reference [1]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [1]: إِهدنا الصراط المستقيم
----------------------------------------------------------------------------------------------------
Reference [2]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [2]: صِرَاطَ الَّذِي نَ أَنْعَمْتَ عَلَيْهِمْ غَيرِ الْمَغْضُوبِ عَلَيهِمْ وَلَا بَامِن
----------------------------------------------------------------------------------------------------
Reference [3]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [4]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [4]: فأَمْدُو لِلَّهِ رَبِّ العَالَنِينَ
----------------------------------------------------------------------------------------------------
Reference [5]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: الْوَاحْمَ لِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [6]: مَالِكِ يَوْمِ الدِّينِ
Prediction [6]: مالك يومِ الدين
----------------------------------------------------------------------------------------------------
Reference [7]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [7]: إيا كان اعبد وا إيا كان الساعين
----------------------------------------------------------------------------------------------------
Reference [8]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [8]: اهْدِينَ الصِّرَاطَة لِلْمُسْتَاقِيمَ
----------------------------------------------------------------------------------------------------
Reference [9]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [9]: لصِرَاقَا الَذِينَا أَنْ عَمْت عَلَيْهِمْ غَيْرِ الْمَغْضُودِ عَلَيْهِمْ وَلَبَّىن

Evaluating samples 141 to 150:
Word Error Rate (WER): 117.95%
Character Error Rate (CER): 72.77%
----------------------------------------------------------------------------------------------------
Reference [0]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: بِسْمِتْ ذَاه رَمَنَه رَحِ
----------------------------------------------------------------------------------------------------
Reference [1]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [1]: فلحمزُونِ اللّهِ يغَبّلعنم
----------------------------------------------------------------------------------------------------
Reference [2]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: لْحَممْ دُونٍلا وَبٍ للَّالينَوَفمَالِووَقِي
----------------------------------------------------------------------------------------------------
Reference [3]: مَالِكِ يَوْمِ الدِّينِ
Prediction [3]: ألعمدوللهوب لللممنوفمايواللاقي مما مدي مِند
----------------------------------------------------------------------------------------------------
Reference [4]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [4]: إنياك ناه ه وإيادر لل استان
----------------------------------------------------------------------------------------------------
Reference [5]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [5]: بِدِنً صِغاطًا  مُنستَنطِيما
----------------------------------------------------------------------------------------------------
Reference [6]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [6]: صِرَا قَلَّذِيِي نَاءَ انَّعىهُمْدَىلَهِهِمْ غَهِيرٍمَوْ غبُوهبِرَالَاهِضَاعِيرٍمَو قُو بِرَارًلَ إِيرِهِمْ وَالَهُمْقَاللِينَ
----------------------------------------------------------------------------------------------------
Reference [7]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: بسم الله الرهمر الرحيم
----------------------------------------------------------------------------------------------------
Reference [8]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [8]: لحمز لله رب العالمون
----------------------------------------------------------------------------------------------------
Reference [9]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: الرَّحْمَنِ الرَّخِيم

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

Evaluating samples 151 to 160:
Word Error Rate (WER): 101.69%
Character Error Rate (CER): 41.41%
----------------------------------------------------------------------------------------------------
Reference [0]: مَالِكِ يَوْمِ الدِّينِ
Prediction [0]: مالد يوم الدين
----------------------------------------------------------------------------------------------------
Reference [1]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [1]: إيَاكَانَ اعبدُ وَإِيَاكَنَستَاعيم
----------------------------------------------------------------------------------------------------
Reference [2]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [2]: اِهْدِنَا الصِّرَاطَ الْمُسْتَطِيمَ
----------------------------------------------------------------------------------------------------
Reference [3]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [3]: صِرَاطَ الَّذِينَ أَنا عَمْتَ عَلَيْهِم غَيرٍ لمَغْهُوبِ علَيْهِمْ وَلَبُّمينَ
----------------------------------------------------------------------------------------------------
Reference [4]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: بسمِ الله الرّحمةن الرحيم اسم ذهك الرصن من لرقي
----------------------------------------------------------------------------------------------------
Reference [5]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [5]: الحَمزُ لِلَّهِ رَدِّ لالَ أَل حَلجُ لِلَّهِ وابِّلآلَمين
----------------------------------------------------------------------------------------------------
Reference [6]: الرَّحْمَٰنِ الرَّحِيمِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: الرَّأمنِ رَّقيم - ألرَّخمانِ مرقي
----------------------------------------------------------------------------------------------------
Reference [7]: مَالِكِ يَوْمِ الدِّينِ مَالِكِ يَوْمِ الدِّينِ
Prediction [7]: مالكي يوم الدين لا يديونلكان
----------------------------------------------------------------------------------------------------
Reference [8]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [8]: إِيّاكَنَ اعبُلُ وَإِيَّاكَنَسداعِينَ - إِيَّا كانَبُدُ وَإِيَّاكَنَتتّاعِينَ
----------------------------------------------------------------------------------------------------
Reference [9]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [9]: اِهدِنا الصراطَ المستقيم - إهدلاصقراق للأُسكطين

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

Evaluating samples 161 to 170:
Word Error Rate (WER): 96.36%
Character Error Rate (CER): 49.44%
----------------------------------------------------------------------------------------------------
Reference [0]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [0]: سصراص الذين ألالتاليهم غير المغضو بياليهم ولأغامن- إغاقلنميل أنا من كاني الغريله الأضوليانيهم ولوقالين
----------------------------------------------------------------------------------------------------
Reference [1]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: بسم اللهم الرخلن الرئ
----------------------------------------------------------------------------------------------------
Reference [2]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [2]: الْحَنْبُلُ اللَّهِ رَبِّ نَالَ
----------------------------------------------------------------------------------------------------
Reference [3]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: أررحمن رواحم
----------------------------------------------------------------------------------------------------
Reference [4]: مَالِكِ يَوْمِ الدِّينِ
Prediction [4]: مَالِكِي يَوْمِ دِ
----------------------------------------------------------------------------------------------------
Reference [5]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [5]: إياكن عبد وإياتاً استائي
----------------------------------------------------------------------------------------------------
Reference [6]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [6]: اهدِنا الصِراطًا المُستط
----------------------------------------------------------------------------------------------------
Reference [7]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [7]: صِرَاطَا الَّذِينَ أَنَا أَمْتَى لَيْهِمْ غَيرِ الْمَغْدُو بِعَلَيْهِمْ ولَبمِِن
----------------------------------------------------------------------------------------------------
Reference [8]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [9]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [9]: الحمد لله رب العالمين

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

Evaluating samples 171 to 180:
Word Error Rate (WER): 81.58%
Character Error Rate (CER): 32.16%
----------------------------------------------------------------------------------------------------
Reference [0]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [1]: مَالِكِ يَوْمِ الدِّينِ
Prediction [1]: مالك يوم الدين
----------------------------------------------------------------------------------------------------
Reference [2]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [2]: إياك نعبد وإياك ناستعيم
----------------------------------------------------------------------------------------------------
Reference [3]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [3]: إِهدِنا الصراطَ المُزتقيم
----------------------------------------------------------------------------------------------------
Reference [4]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [4]: صِرَاطَ الَّذِينَ أَنَأَمْتَ عَلَيْهِمْ غَيْرِي الْمَغْضُوبِ عَلَيْهِمْ وَلَا لضَّالِّي
----------------------------------------------------------------------------------------------------
Reference [5]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: بِسْمِ اللَّهِ الرَّحِمَنِ الرَّحِ
----------------------------------------------------------------------------------------------------
Reference [6]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [6]: الْحَمْدُ لِلَّهِ رَبٍّ لعَالَم
----------------------------------------------------------------------------------------------------
Reference [7]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [8]: مَالِكِ يَوْمِ الدِّينِ
Prediction [8]: مالِك يون الدين
----------------------------------------------------------------------------------------------------
Reference [9]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [9]: إيا كنعبد وإياك نستعن

Evaluating samples 181 to 190:
Word Error Rate (WER): 84.44%
Character Error Rate (CER): 26.74%
----------------------------------------------------------------------------------------------------
Reference [0]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [0]: إِهدِينَا الصِّلَاطًة للْمُسْتَقِيم
----------------------------------------------------------------------------------------------------
Reference [1]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [1]: وِرَاقَى الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيرِنِ مَضُّوبِ عَلَيْهِمْ وَلَضَّالن
----------------------------------------------------------------------------------------------------
Reference [2]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [3]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [3]: الْحَمْزُ لِلَّهِ رَبِّ الآدَمينِ
----------------------------------------------------------------------------------------------------
Reference [4]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [5]: مَالِكِ يَوْمِ الدِّينِ
Prediction [5]: مَالِكِ يَوْمِ الدِّينِ
----------------------------------------------------------------------------------------------------
Reference [6]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [6]: إِيَّاكَ نَعْبُلُ وَإِيَّاكَ نَشْتَعِيمٍ
----------------------------------------------------------------------------------------------------
Reference [7]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [7]: اهْدِينَا اصطِرَاطقَىالمُستَقِيمِ
----------------------------------------------------------------------------------------------------
Reference [8]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [8]: صِرَاقَا الَّذِي لَأَلْعَمْسَ عَلَيْنِالغَيرِ الْمَغْبُوبِ عَلَيْهِمْ وَلَفَال
----------------------------------------------------------------------------------------------------
Reference [9]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: بسم الله الرحمن الرحيم

Evaluating samples 191 to 200:
Word Error Rate (WER): 105.26%
Character Error Rate (CER): 30.52%
----------------------------------------------------------------------------------------------------
Reference [0]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [0]: أالْحَمْدُ لِلَّهِ رَبٍّ عَ لَمين
----------------------------------------------------------------------------------------------------
Reference [1]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: الرَّحْمَنِ الرَّحِيمٌ
----------------------------------------------------------------------------------------------------
Reference [2]: مَالِكِ يَوْمِ الدِّينِ
Prediction [2]: مالك يوم الدين
----------------------------------------------------------------------------------------------------
Reference [3]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [3]: إِيَّا كَنَ اعْبُدُ وَإِيَّا كَنَ اسْتَعِينِ
----------------------------------------------------------------------------------------------------
Reference [4]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [4]: اهْدِي نَصِّرَة قَا الْمُسْتَقِيمٌ
----------------------------------------------------------------------------------------------------
Reference [5]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [5]: صِرَاقَى الَّذِينَ أَنْعَمْتَ عَلَيهِمْ غَيرِ لمَقُوبِ عَلَيْهِمْ ولَا البِّلِينِ
----------------------------------------------------------------------------------------------------
Reference [6]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [7]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [7]: الْحَمْد لِله رَبِّ عَالَم
----------------------------------------------------------------------------------------------------
Reference [8]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [9]: مَالِكِ يَوْمِ الدِّينِ
Prediction [9]: مالك يوم الدي

Evaluating samples 201 to 210:
Word Error Rate (WER): 104.44%
Character Error Rate (CER): 34.90%
----------------------------------------------------------------------------------------------------
Reference [0]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [0]: إيا كن اعبد وإيا كنا ستا
----------------------------------------------------------------------------------------------------
Reference [1]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [1]: دين الصراط المستقل مم
----------------------------------------------------------------------------------------------------
Reference [2]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [2]: لسَرَاطَ الَّذِينَ أَنْ عَمْتَ عَلَيْهِمْ غَيْرِ المَبْضُولِ عَلَيْهِمْ وَلَقَالم
----------------------------------------------------------------------------------------------------
Reference [3]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [4]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [4]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
----------------------------------------------------------------------------------------------------
Reference [5]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [6]: مَالِكِ يَوْمِ الدِّينِ
Prediction [6]: مَالِكِي يَومِ الدِِّينِ
----------------------------------------------------------------------------------------------------
Reference [7]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [7]: إِيَّا كَانَ اعْبُدٌ وَإِيَّا كَنَ اسْتَعِيينَ
----------------------------------------------------------------------------------------------------
Reference [8]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [8]: اهدِنا الصراط المُستقِيم
----------------------------------------------------------------------------------------------------
Reference [9]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [9]: صراطا لذين أن عمت عليهم غير المغبمب عليهم ولا قالن عمين

Evaluating samples 211 to 220:
Word Error Rate (WER): 100.00%
Character Error Rate (CER): 37.70%
----------------------------------------------------------------------------------------------------
Reference [0]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [1]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [1]: الحمض لله رب العالمن
----------------------------------------------------------------------------------------------------
Reference [2]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [3]: مَالِكِ يَوْمِ الدِّينِ
Prediction [3]: ماله يوم الدين
----------------------------------------------------------------------------------------------------
Reference [4]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [4]: إياك نعبد وإياك نستعين
----------------------------------------------------------------------------------------------------
Reference [5]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [5]: اهدنا الصراف المستقيم
----------------------------------------------------------------------------------------------------
Reference [6]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [6]: صِغَاقَى الَّذِينَ أَنْ عَمْتَ عَلَيْهِمْ غَيرِ المَغنُوبِ عَلَيهِمْ ولَا مُل
----------------------------------------------------------------------------------------------------
Reference [7]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: بِسْمِ اللَهِ الرَّحْمَنِ الرّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [8]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [8]: الحمدري له رب لعالمٍ
----------------------------------------------------------------------------------------------------
Reference [9]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: الرَّحْمَن عَنِ الرَّحِيم

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

Evaluating samples 221 to 230:
Word Error Rate (WER): 100.00%
Character Error Rate (CER): 25.72%
----------------------------------------------------------------------------------------------------
Reference [0]: مَالِكِ يَوْمِ الدِّينِ
Prediction [0]: مالك يوم الدي
----------------------------------------------------------------------------------------------------
Reference [1]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [1]: إيا كن اعبد وإيا كان استعي
----------------------------------------------------------------------------------------------------
Reference [2]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [2]: إهدِينَا الصِرَا - قَلْمُسْتَقِيمَ
----------------------------------------------------------------------------------------------------
Reference [3]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [3]: الصِرَاطَ الَّذِينَ أَنَّ عِمْتَ عَلَيْهِمْ غَيرِ لِمَغْضُوبِ عَلَيْهِمْ وَلَضَىدِِنِ
----------------------------------------------------------------------------------------------------
Reference [4]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [5]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [5]: لْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
----------------------------------------------------------------------------------------------------
Reference [6]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [6]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [7]: مَالِكِ يَوْمِ الدِّينِ
Prediction [7]: مَالِكِ يَومِ الدِّينِ
----------------------------------------------------------------------------------------------------
Reference [8]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [8]: إِيَّا كَنَ عْبُدُ وَإِيَا كَنَى اسْتَعِينَ
----------------------------------------------------------------------------------------------------
Reference [9]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [9]: اهْدِينَا الصِّرَاطَ الْمُسْتَقِيمَ

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

Evaluating samples 231 to 240:
Word Error Rate (WER): 90.67%
Character Error Rate (CER): 55.35%
----------------------------------------------------------------------------------------------------
Reference [0]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [0]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَضَال
----------------------------------------------------------------------------------------------------
Reference [1]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [2]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [2]: الحَمْدُ لِلَّهِ رَبِّ الْعَالَمنِ
----------------------------------------------------------------------------------------------------
Reference [3]: الرَّحْمَٰنِ الرَّحِيمِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [3]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [4]: مَالِكِ يَوْمِ الدِّينِ مَالِكِ يَوْمِ الدِّينِ
Prediction [4]: مالك يوم الدين
----------------------------------------------------------------------------------------------------
Reference [5]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [5]: إيا كنعبد وإيا كان ستعين
----------------------------------------------------------------------------------------------------
Reference [6]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [6]: إهدِينَ الصراطَ المُستَقِمِ
----------------------------------------------------------------------------------------------------
Reference [7]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [7]: صِراطَا الَّذِينَ أَدْن عَمْتَ عَلَيهِم غَيرِ المَغضُوبِ عَلَيهِم  ولَاضالنِ
----------------------------------------------------------------------------------------------------
Reference [8]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [8]: بسم اللن الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [9]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [9]: الْحَمْدُ لِلَّه رَبِّ الْعَالَمِنِ

Evaluating samples 241 to 250:
Word Error Rate (WER): 105.26%
Character Error Rate (CER): 39.73%
----------------------------------------------------------------------------------------------------
Reference [0]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [0]: الرَّحْمَنِ الرَّحِيم
----------------------------------------------------------------------------------------------------
Reference [1]: مَالِكِ يَوْمِ الدِّينِ
Prediction [1]: مالك يوم الدين
----------------------------------------------------------------------------------------------------
Reference [2]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [2]: إيا كنعبد وإيا كان ستعين
----------------------------------------------------------------------------------------------------
Reference [3]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [3]: إهدِينَ الصراطَةَ المُستقِم
----------------------------------------------------------------------------------------------------
Reference [4]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [4]: صراطا الذين أد عمت عليهم غير المغضوب عليهم  ولبالن
----------------------------------------------------------------------------------------------------
Reference [5]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [5]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [6]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [6]: بَلْحَمْدُ لِلَّهِ رَبِّ العَالَم
----------------------------------------------------------------------------------------------------
Reference [7]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [7]: يالرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [8]: مَالِكِ يَوْمِ الدِّينِ
Prediction [8]: مَالِكِ يَومِ الدِّين
----------------------------------------------------------------------------------------------------
Reference [9]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [9]: إِيَّا كَانَ عْبُدٌ وَإِيَا كأنَ اسْتَعِ

[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping

Evaluating samples 251 to 260:
Word Error Rate (WER): 104.44%
Character Error Rate (CER): 32.36%
----------------------------------------------------------------------------------------------------
Reference [0]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [0]: إِهْدِي نَصِرَاطَا الْمُسْتَقِيم
----------------------------------------------------------------------------------------------------
Reference [1]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [1]: صِراطَا لَّذِينَ أَنعَمتَ عالَيهِم غَيرِ لمَغْبُو بِعالَيهِم وَلا بّالِن
----------------------------------------------------------------------------------------------------
Reference [2]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [2]: بسم الله الرحمن الرحيم
----------------------------------------------------------------------------------------------------
Reference [3]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [3]: أالحَمْدُ لِلَّهِ رَبِّ العالَمنِ
----------------------------------------------------------------------------------------------------
Reference [4]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [4]: الرَّحْمَنِ الرَّحِيمِ
----------------------------------------------------------------------------------------------------
Reference [5]: مَالِكِ يَوْمِ الدِّينِ
Prediction [5]: مَالِكِ يَوُمِ الدِّينِ
----------------------------------------------------------------------------------------------------
Reference [6]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [6]: إِيَّا كَانَ أعْبُدُو وَإِيَّا كَنَ استَعين
----------------------------------------------------------------------------------------------------
Reference [7]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [7]: اهْدِنَا الصِّرَاطَى الْمُسْتَقِيمَ
----------------------------------------------------------------------------------------------------
Reference [8]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [8]: صِراطَ الَّذِينَ أَنْ عَمْتَ عَلَيْهِمْ غَيْرِي الْمَغْدُوبِ عَلَيْهِمْ وَلَضَّى
----------------------------------------------------------------------------------------------------
Reference [9]: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
Prediction [9]: أعود بالله لنى شيصان الرجيبسم الله الرحمن الرح

Evaluating samples 261 to 266:
Word Error Rate (WER): 96.00%
Character Error Rate (CER): 31.71%
----------------------------------------------------------------------------------------------------
Reference [0]: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
Prediction [0]: الحمد لله ربّ العلمين
----------------------------------------------------------------------------------------------------
Reference [1]: الرَّحْمَٰنِ الرَّحِيمِ
Prediction [1]: الرَّحْمَنِ الرَّحِي
----------------------------------------------------------------------------------------------------
Reference [2]: مَالِكِ يَوْمِ الدِّينِ
Prediction [2]: مالك ليون الدّي
----------------------------------------------------------------------------------------------------
Reference [3]: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
Prediction [3]: إِيَّا كَنَ اعْبُدُ وَإِيَّاكَنَ استَعِيلُ
----------------------------------------------------------------------------------------------------
Reference [4]: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
Prediction [4]: وهدين الصراط المستطيم
----------------------------------------------------------------------------------------------------
Reference [5]: صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
Prediction [5]: صِرَاطَ الَّذِينَ أَنْ عَمْتَ عَلَيْهِمْغَيْرِ الْمَغْنُوبِ عَلَيْهِمْ و لَادْبَالي

# Training

In [24]:
import librosa
import torch
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC, Trainer, TrainingArguments
from datasets import Dataset
import numpy as np

# Prepare data for training: Load the audio and process it
def prepare_data_for_training(dataset):
    input_values = []
    labels = []
    
    for index, row in dataset.iterrows():
        # Load the audio file using librosa
        speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
        
        # Preprocess the speech data with the processor
        inputs = processor(speech_array, sampling_rate=16_000, return_tensors="pt", padding=True)
        input_values.append(inputs.input_values.squeeze().numpy())
        
        # Encode the target transcription (label)
        with processor.as_target_processor():
            label_ids = processor(row["TRANSCRIPT"]).input_ids
        labels.append(label_ids)
    
    return input_values, labels

# Prepare the dataset
input_values, labels = prepare_data_for_training(poc_transcript_df)

# Create a Hugging Face Dataset object
dataset = Dataset.from_dict({"input_values": input_values, "labels": labels})

# Define data collator to process batches dynamically
def data_collator(features):
    input_features = [{"input_values": feature["input_values"]} for feature in features]
    label_features = [{"input_ids": feature["labels"]} for feature in features]
    
    batch = processor.pad(input_features, padding=True, return_tensors="pt")
    with processor.as_target_processor():
        labels_batch = processor.pad(label_features, padding=True, return_tensors="pt")

    labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)
    
    batch["labels"] = labels
    return batch

# Define the training arguments
training_args = TrainingArguments(
    output_dir="./wav2vec2-finetuned", # Save directory
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    evaluation_strategy="steps",
    num_train_epochs=3,  # You can adjust this
    save_steps=400,
    eval_steps=400,
    logging_steps=400,
    save_total_limit=2,
    learning_rate=1e-4,
    warmup_steps=500,
    save_strategy="epoch"
)

# Initialize Trainer for model fine-tuning
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset,
    tokenizer=processor.feature_extractor
)

# Train the model
trainer.train()

# Save the model and processor
model.save_pretrained("./wav2vec2-finetuned")
processor.save_pretrained("./wav2vec2-finetuned")

[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (736) too large for available bit count (728)
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (768) too large for available bit count (736)
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (928) too large for available bit count (920)
[src/libmpg123/layer3.c:INT123_do_layer3():1801] error: dequantization failed!
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (2016) too large for available bit count (1856)
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (960) too large for available bit count (928)
[src/libmpg123/layer3.c:INT123_do_layer3():1801] error: dequantization failed!
[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (992) too large for available bit count (928)
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
[src/libmpg123/id3.c:INT123_parse_new_id3():947] warning: ID3v2: unrealistic small tag lengh 0, skipping
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:155: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(

/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:155: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:155: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(

Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7ff1fd5be690>> (for post_run_cell), with arguments args (<ExecutionResult object at 7ff15221edd0, execution_count=24 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7ff15ec04d50, raw_cell="import librosa
import torch
from transformers impo.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/YoussefENSI_backup/Fiver%20Work/Arkani/ArkaniPOC/notebooks/starter.ipynb#X30sZmlsZQ%3D%3D> result=None>,),kwargs {}:

TypeError: _WandbInit._pause_backend() takes 1 positional argument but 2 were given

In [26]:
import wandb
wandb.finish()

Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7ff1fd5be690>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7ff152227c50, raw_cell="import wandb
wandb.finish()
" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/c%3A/YoussefENSI_backup/Fiver%20Work/Arkani/ArkaniPOC/notebooks/starter.ipynb#X33sZmlsZQ%3D%3D>,),kwargs {}:

TypeError: _WandbInit._resume_backend() takes 1 positional argument but 2 were given

wandb: WARNING Source type is set to 'repo' but some required information is missing from the environment. A job will not be created from this run. See https://docs.wandb.ai/guides/launch/create-job

In [27]:
# Save the model and processor
model.save_pretrained("./wav2vec2-finetuned")
processor.save_pretrained("./wav2vec2-finetuned")

# Interference

In [29]:
import pandas as pd
import librosa
import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor

# Load the fine-tuned model and processor
model = Wav2Vec2ForCTC.from_pretrained("./wav2vec2-finetuned")
processor = Wav2Vec2Processor.from_pretrained("./wav2vec2-finetuned")

# Function to process a batch of files
def process_audio_batch(dataset):
    predictions = []
    for index, row in dataset.iterrows():
        # Load the audio file using librosa
        speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
        
        # Process the audio file with the processor
        inputs = processor(speech_array, sampling_rate=16_000, return_tensors="pt", padding=True)

        # Pass the inputs through the model
        with torch.no_grad():
            logits = model(inputs.input_values, attention_mask=inputs.attention_mask).logits

        # Get the predicted ids and decode them
        predicted_ids = torch.argmax(logits, dim=-1)
        predicted_sentence = processor.batch_decode(predicted_ids)
        
        # Store the predicted sentence
        predictions.append(predicted_sentence[0])
    
    return predictions

# Iterate over the entire dataset and save predictions and references
def get_predictions_df(dataset, batch_size=10):
    total_samples = len(dataset)
    predictions = []

    for i in range(0, total_samples, batch_size):
        # Select the current batch of data
        batch_data = dataset.iloc[i:i+batch_size].reset_index(drop=True)
        
        # Process the batch and get predictions
        batch_predictions = process_audio_batch(batch_data)
        predictions.extend(batch_predictions)
    
    # Store predictions and references in a DataFrame
    result_df = pd.DataFrame({
        "Reference": dataset["TRANSCRIPT"],
        "Prediction": predictions
    })
    
    return result_df

# Load the dataset
# Assuming 'transcript_df' is your full dataset
poc_transcript_df = transcript_df.reset_index(drop=True)

# Get predictions and references DataFrame
predictions_df = get_predictions_df(poc_transcript_df, batch_size=10)

/tmp/ipykernel_69/3296485077.py:15: UserWarning: PySoundFile failed. Trying audioread instead.
  speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
/usr/local/lib/python3.11/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/1/Quran_Ayat_public/audio_data/AbdulSamad_64kbps/002110.mp3'

In [ ]:
from jiwer import wer, cer

# Function to evaluate the predictions using Word Error Rate (WER) and Character Error Rate (CER)
def evaluate_predictions(df):
    references = df["Reference"].tolist()
    predictions = df["Prediction"].tolist()
    
    # Calculate WER and CER
    wer_score = wer(references, predictions)
    cer_score = cer(references, predictions)
    
    print(f"Word Error Rate (WER): {wer_score * 100:.2f}%")
    print(f"Character Error Rate (CER): {cer_score * 100:.2f}%")

# Evaluate the model using the predictions DataFrame
evaluate_predictions(predictions_df)

In [31]:
import pandas as pd
import librosa
import torch
from jiwer import wer, cer

# Initialize an empty DataFrame to store references and predictions
results_df = pd.DataFrame(columns=["Reference", "Prediction"])

# Function to process a batch of files
def process_audio_batch(dataset):
    predictions = []
    for index, row in dataset.iterrows():
        # Load the audio file using librosa
        speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
        
        # Process the audio file with the processor
        inputs = processor(speech_array, sampling_rate=16_000, return_tensors="pt", padding=True)

        # Pass the inputs through the model
        with torch.no_grad():
            logits = model(inputs.input_values, attention_mask=inputs.attention_mask).logits

        # Get the predicted ids and decode them
        predicted_ids = torch.argmax(logits, dim=-1)
        predicted_sentence = processor.batch_decode(predicted_ids)
        
        # Store the predicted sentence
        predictions.append(predicted_sentence[0])
    
    return predictions

# Function to evaluate the predictions using Word Error Rate (WER) and Character Error Rate (CER)
def evaluate_model(dataset, predictions):
    global results_df
    
    # Initialize lists to store reference and predicted sentences
    references = dataset["TRANSCRIPT"].tolist()
    predicted = predictions
    
    # Calculate WER and CER
    wer_score = wer(references, predicted)
    cer_score = cer(references, predicted)
    
    print(f"Word Error Rate (WER): {wer_score * 100:.2f}%")
    print(f"Character Error Rate (CER): {cer_score * 100:.2f}%")
    
    # Append results to the DataFrame
    for i, predicted_sentence in enumerate(predicted):
        # Print reference and prediction side-by-side for inspection
        print("-" * 100)
        print(f"Reference [{i}]:", references[i])
        print(f"Prediction [{i}]:", predicted_sentence)
        
        # Add the reference and prediction to the results DataFrame
        results_df = results_df.append({
            "Reference": references[i],
            "Prediction": predicted_sentence
        }, ignore_index=True)

# Iterate over the entire dataset and evaluate every 10 samples
def evaluate_in_batches(dataset, batch_size=10):
    total_samples = len(dataset)
    for i in range(0, total_samples, batch_size):
        # Select the current batch of data
        batch_data = dataset.iloc[i:i+batch_size].reset_index(drop=True)
        
        # Process the batch and get predictions
        predicted_sentences = process_audio_batch(batch_data)
        
        # Evaluate the model predictions every 10 samples
        print(f"\nEvaluating samples {i+1} to {min(i+batch_size, total_samples)}:")
        evaluate_model(batch_data, predicted_sentences)

# Load the dataset filtered by Surah 'الفاتحة'
poc_transcript_df = transcript_df[transcript_df['SOURAH'] == 'الفاتحة'].sample(30).reset_index(drop=True)

# Evaluate on all the data, calculating results every 10 samples
evaluate_in_batches(poc_transcript_df, batch_size=10)

# Save the DataFrame to a CSV file after evaluation
results_df.to_csv("evaluation_results.csv", index=False)

/tmp/ipykernel_69/607359550.py:14: UserWarning: PySoundFile failed. Trying audioread instead.
  speech_array, sampling_rate = librosa.load(row["PATH"], sr=16_000)
/usr/local/lib/python3.11/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/1/Quran_Ayat_public/audio_data/Muhammad_Jibreel_64kbps/001002.mp3'